const stories = [
     {
          id: "fbsyg3fuveznhnt3",
		title: "Si Kancil dan Buaya",
		category: "Fabel",
		origin: "Nusantara",
          imageId: "100",
		storyDesc: [
               "Pada suatu hari yang cerah, di sebuah hutan yang rindang, hiduplah seekor kancil kecil yang cerdik bernama Kancil. Kancil suka berpetualang di hutan, mencari makan dan bermain dengan teman-temannya. Suatu hari, setelah berkeliling hutan, Kancil merasa sangat haus. Dia ingin pergi ke sungai untuk minum air yang segar dan dingin.",
               "\n \n",
               "Saat Kancil sampai di tepi sungai, dia melihat ada banyak buaya sedang berjemur di sana. Kancil tahu bahwa buaya-buaya itu bisa sangat berbahaya. Dia berpikir keras, mencari cara agar bisa minum air tanpa dimakan oleh buaya-buaya tersebut. Tiba-tiba, Kancil mendapatkan ide yang sangat cerdik!",
               "\n \n",
               "Kancil mendekati salah satu buaya yang besar dan berkata dengan suara yang lantang,",
               "\n",
               "<em>\"Halo Buaya! Aku punya kabar baik! Raja Hutan ingin membagikan makanan kepada kalian semua. Tapi, Raja Hutan perlu tahu berapa jumlah buaya di sungai ini.\"</em>",
               "\n \n",
               "Buaya besar itu merasa senang mendengar kabar tersebut.",
               "\n",
               "<em>\"Benarkah, Kancil? Bagaimana caranya Raja Hutan akan menghitung kami\"</em> tanyanya.",
               "\n \n",
               "Kancil menjawab, ",
               "\n",
               "<em>\"Mudah sekali! Kalian semua harus berbaris dari sini sampai ke seberang sungai, agar aku bisa menghitung kalian satu per satu.\"</em>",
               "\n \n",
               "Buaya besar itu lalu memerintahkan semua buaya untuk berbaris dari tepi sungai sampai ke seberang. Mereka segera berbaris dengan rapi, menyambung dari satu buaya ke buaya lainnya.",
               "\n \n",
               "Kancil mulai melompat ke punggung buaya pertama sambil berkata,",
               "\n",
               "<em>\"Satu!\"</em>",
               "\n",
               "Lalu dia melompat ke punggung buaya kedua sambil berkata,",
               "\n",
               "<em>\"Dua!\"</em>",
               "\n",
               "Kancil terus melompat dari satu buaya ke buaya lainnya, sambil menghitung dengan keras,",
               "<em>\"Tiga, empat, lima...\"</em>",
               "\n",
               "Hingga akhirnya dia sampai di seberang sungai.",
               "\n \n",
               "Setelah sampai di seberang sungai, Kancil melompat ke tanah kering dan berkata,",
               "\n",
               "<em>\"Terima kasih, Buaya! Sekarang aku sudah tahu berapa jumlah kalian.\"</em>",
               "\n \n",
               "Buaya-buaya itu bertanya,",
               "\n",
               "\"Berapa jumlah kami, Kancil?\"",
               "\n \n",
               "Kancil tertawa dan berkata,",
               "\n",
               "<em>\"Jumlah kalian cukup banyak, tapi aku hanya butuh menyeberang sungai agar bisa minum air segar. Terima kasih sudah membantu! Selamat tinggal, Buaya!\"</em>",
               "\n \n",
               "Para buaya marah karena merasa tertipu, tetapi mereka tidak bisa berbuat apa-apa. Kancil sudah berada di seberang sungai dan minum air dengan aman. Kancil pun pergi dengan senang hati setelah minum air yang segar.",
          ].join(""),
          morals: [
               "Cerita ini mengajarkan kita bahwa <strong>kecerdikan</strong> dan <strong>pikiran</strong> yang cerdas bisa mengatasi segala tantangan. Kancil yang kecil dan lemah bisa menipu buaya-buaya yang besar dan kuat dengan kepintarannya.",
          ].join(""),
          synopsis: [
               "Suatu hari, Kancil yang cerdik merasa haus. Untuk minum air sungai yang dijaga buaya, Kancil menipu buaya dengan berpura-pura menghitung mereka.",
          ].join(""),
     },
     {
          id: "fbpznbbcwh54ifzm",
          title: "Kelinci dan Kura-Kura",
          category: "Fabel",
          origin: "Nusantara",
          imageId: "101",
          storyDesc: [
               "Pada suatu hari yang cerah di hutan, hiduplah dua sahabat yang sangat berbeda. Kelinci, yang terkenal karena kecepatannya, dan Kura-Kura, yang dikenal karena kesabarannya. Keduanya sering menghabiskan waktu bersama, meskipun kelinci sering mengejek kura-kura karena lambat.",
               "\n \n",
               "Suatu hari, Kelinci dengan sombong berkata kepada Kura-Kura,",
               "\n",
               "<em>\"Kura-Kura, kamu ini sangat lambat. Aku yakin aku bisa berlari mengelilingi hutan ini berkali-kali sebelum kamu sampai di garis finish.\"</em> Kura-Kura, yang biasanya diam dan sabar, merasa tertantang dengan ejekan Kelinci.",
               "\n \n",
               "Kura-Kura menjawab dengan tenang, <em>\"Bagaimana kalau kita mengadakan perlombaan lari? Kita akan lihat siapa yang lebih cepat.\"</em>",
               "\n",
               "Kelinci tertawa terbahak-bahak mendengar tantangan itu. Dengan penuh keyakinan, Kelinci setuju untuk berlomba dengan Kura-Kura. Mereka pun memilih hari dan jalur untuk perlombaan tersebut.",
               "\n \n",
               "Pada hari yang telah ditentukan, hewan-hewan di hutan berkumpul untuk menyaksikan perlombaan antara Kelinci dan Kura-Kura. Rusa, sebagai wasit, memulai perlombaan dengan meniup peluit. Kelinci segera melesat meninggalkan Kura-Kura jauh di belakang. Dia berlari dengan cepat, melompati batu dan akar pohon, sementara Kura-Kura berjalan dengan kecepatan biasa, namun dengan langkah yang mantap.",
               "\n \n",
               "Setelah merasa sangat jauh di depan, Kelinci berpikir, <em>\"Kura-Kura pasti masih sangat jauh di belakang. Aku punya banyak waktu untuk beristirahat.\"</em>",
               "\n",
               "Kelinci menemukan tempat yang teduh di bawah pohon dan memutuskan untuk tidur sejenak. Sementara itu, Kura-Kura terus berjalan tanpa henti, meskipun pelan, dia tidak pernah berhenti.",
               "\n \n",
               "Seiring berjalannya waktu, Kura-Kura semakin mendekati tempat Kelinci tertidur. Hewan-hewan di hutan menyaksikan dengan penuh perhatian. Mereka kagum melihat kesabaran dan ketekunan Kura-Kura. Akhirnya, Kura-Kura melewati Kelinci yang masih tertidur di bawah pohon.",
               "\n \n",
               "Ketika matahari sudah hampir terbenam, Kelinci terbangun dari tidurnya. Dia meregangkan badannya dan melihat sekeliling. Betapa terkejutnya dia melihat Kura-Kura sudah hampir mencapai garis finish. Kelinci segera berlari secepat mungkin, mencoba mengejar Kura-Kura. Namun, terlambat, dengan langkah terakhirnya, Kura-Kura berhasil menyentuh garis finish tepat sebelum Kelinci tiba.",
               "\n \n",
               "Hewan-hewan di hutan bersorak gembira dan memberikan selamat kepada Kura-Kura. Mereka memuji ketekunan dan kesabarannya.",
               "\n",
               "Kelinci merasa malu atas kesombongannya dan belajar pelajaran berharga hari itu. Dia menghampiri Kura-Kura dan berkata, <em>\"Kura-Kura, kamu memang lambat, tetapi kamu telah mengalahkanku dengan ketekunan dan kesabaranmu. Aku belajar banyak hari ini.\"</em>",
               "\n \n",
               "Kura-Kura tersenyum dan berkata, <em>\"Tidak masalah, Kelinci. Yang penting adalah kita tidak menyerah dan terus berjalan meskipun lambat. Ketekunan dan kesabaran adalah kunci keberhasilan.\"</em>",
               "\n \n",
               "Sejak hari itu, Kelinci dan Kura-Kura tetap bersahabat, tetapi Kelinci tidak pernah lagi meremehkan Kura-Kura. Mereka belajar bahwa setiap makhluk memiliki kelebihan dan kelemahan masing-masing. Kisah mereka menjadi legenda di hutan, diceritakan dari generasi ke generasi sebagai pelajaran tentang kerendahan hati, ketekunan, dan kesabaran.",
          ].join(""),
          morals: [
               "Cerita ini mengajarkan kita bahwa <strong>kesabaran</strong> dan <strong>ketekunan</strong> bisa mengalahkan kecepatan dan kesombongan. Kura-Kura yang lambat namun gigih berhasil memenangkan perlombaan melawan Kelinci yang cepat namun sombong. Kisah ini mengingatkan kita untuk selalu rendah hati dan tidak meremehkan orang lain.",
          ].join(""),
          synopsis: [
               "Kelinci menantang Kura-Kura lomba lari. Namun karena kesombongannya Kelinci langsung berlari dan tidur di tengah lomba, di sisi lain Kura-Kura dengan sabar terus berjalan dan akhirnya menang.",
          ].join(""),
     },
     {
          id: "fbt1gpv6ldm3ybak",
          title: "Semut dan Belalang",
          category: "Fabel",
          origin: "Nusantara",
          imageId: "102",
          storyDesc: [
               "Di sebuah ladang yang subur di Nusantara, hiduplah dua sahabat yang sangat berbeda, yaitu semut dan belalang. Semut adalah makhluk yang rajin bekerja dan selalu bekerja keras untuk menyimpan makanan untuk musim kemarau. Sementara itu, belalang adalah makhluk yang senang bermain dan tidak suka bekerja keras.",
               "\n \n",
               "Setiap hari, semut bekerja keras mengumpulkan biji-bijian dan menyimpannya di gudang untuk menyambut musim kemarau. Belalang, di sisi lain, hanya bersantai dan menikmati hari-harinya tanpa memikirkan masa depan.",
               "\n \n",
               "Suatu hari, ketika musim kemarau tiba, belalang menyadari bahwa dia tidak memiliki makanan. Dia merasa panik dan lapar karena tidak memiliki cadangan makanan seperti semut. Belalang kemudian pergi ke rumah semut dan memohon agar diberi sedikit makanan.",
               "\n \n",
               "Semut, yang melihat kondisi belalang, merasa kasihan. Namun, dia juga tidak bisa memberikan makanan secara cuma-cuma karena stoknya terbatas.",
               "\n",
               "Semut dengan sabar menjelaskan kepada belalang, <em>\"Sahabat, aku sangat berusaha keras untuk menyimpan makanan ini untuk musim kemarau. Aku hanya memiliki cukup makanan untuk keluargaku sendiri.\"</em>",
               "\n \n",
               "Belalang menyesal karena telah menyia-nyiakan waktu dan tidak mempersiapkan dirinya untuk masa sulit. Dia merasa bersalah kepada semut dan berjanji untuk belajar dari kesalahannya. Belalang kemudian pergi dengan hati yang berat, berusaha mencari makanan di ladang yang kering.",
               "\n \n",
               "Sementara itu, semut tetap bekerja keras untuk menyimpan makanan tambahan. Dia juga memberikan sedikit makanan kepada belalang setiap kali dia melihatnya mencari makanan. Meskipun belalang telah belajar dari kesalahannya, dia tetap menghargai bantuan dan kebaikan semut.",
               "\n \n",
               "Musim kemarau berlalu, dan hujan akhirnya turun kembali. Ladang-ladang kembali hijau, dan makanan menjadi melimpah kembali. Semut dan belalang kembali ke kebiasaan mereka masing-masing. Namun, kali ini, belalang juga belajar untuk bekerja keras dan menyimpan makanan untuk masa depan.",
          ].join(""),
          morals: [
               "Cerita ini mengajarkan kita tentang pentingnya kerja keras, persiapan, dan kebijaksanaan dalam menghadapi masa sulit. Semut, dengan kerja kerasnya, berhasil melewati musim kemarau dengan baik, sementara belalang, yang tidak mempersiapkan dirinya, mengalami kesulitan. Namun, belalang belajar dari kesalahannya dan belajar untuk bekerja keras setelah menghadapi masa sulit.",
          ].join(""),
          synopsis: [
               "Semut bekerja keras menyimpan makanan sementara belalang hanya bermain. Ketika kemarau tiba, mereka kelaparan dan meminta bantuan semut. Meski makanan terbatas, semut tetap membantu mereka.",
          ].join(""),
     },
     {
          id: "fb4ecammoldozlyl",
          title: "Bebek Buruk Rupa",
          category: "Fabel",
          origin: "Nusantara",
          imageId: "103",
          storyDesc: [
               "Di sebuah desa di Nusantara, hiduplah seekor bebek yang sangat buruk rupa. Bulunya kusam, paruhnya bengkok, dan kakinya kecil. Bebek ini sering diolok-olok oleh bebek-bebek lain di sekitarnya karena penampilannya yang tidak menarik. Namun, bebek ini memiliki hati yang baik dan selalu bersikap ramah terhadap siapa pun.",
               "\n \n",
               "Suatu hari, desa tersebut dikunjungi oleh seekor burung rajawali yang gagah perkasa. Semua hewan di desa sangat kagum dengan keindahan dan keperkasaan rajawali. Mereka semua berusaha menarik perhatian rajawali, kecuali bebek buruk rupa. Bebek tersebut merasa bahwa dia tidak akan pernah mendapatkan perhatian rajawali karena penampilannya yang buruk.",
               "\n \n",
               "Namun, saat rajawali hendak pergi, dia melihat bebek buruk rupa dan terkesan dengan kebaikan hatinya.",
               "\n",
               "Rajawali memutuskan untuk mendekati bebek tersebut. <em>\"Hai, bebek kecil. Apa yang membuatmu begitu berbeda dari yang lain?\"</em> tanya rajawali dengan ramah.",
               "\n \n",
               "Bebek buruk rupa tersentuh dengan perhatian rajawali.",
               "\n",
               "Dia menjawab, <em>\"Saya memang tidak seindah atau sekuat seperti kamu, tapi saya selalu berusaha menjadi baik dan ramah kepada orang lain.\"</em>",
               "\n \n",
               "Rajawali tersenyum, <em>\"Kamu memiliki hati yang baik, dan itu yang paling penting. Bagaimana jika kamu menjadi temanku? Bersama-sama, kita bisa menjelajahi dunia dan belajar satu sama lain.\"</em>",
               "\n \n",
               "Bebek buruk rupa sangat bahagia mendengar tawaran rajawali. Mereka pun menjadi sahabat yang tak terpisahkan. Rajawali mengajarkan bebek buruk rupa tentang kekuatan dan keindahan di dalam hati, sedangkan bebek buruk rupa mengajarkan rajawali tentang kesederhanaan dan kebaikan.",
               "\n \n",
               "Ketika rajawali terbang tinggi di langit, bebek buruk rupa berenang di danau. Meskipun mereka berdua sangat berbeda, mereka saling melengkapi satu sama lain. Mereka menunjukkan kepada semua hewan di desa bahwa penampilan fisik bukanlah segalanya, dan yang terpenting adalah hati yang baik dan kebaikan.",
          ].join(""),
          morals: [
               "Cerita ini mengajarkan kita bahwa <strong>kebaikan hati</strong> dan <strong>sikap ramah</strong> jauh lebih berharga daripada penampilan fisik.",
               "Meskipun bebek buruk rupa tidak memiliki penampilan yang menarik, dia memiliki <strong>hati yang baik dan ramah terhadap orang lain</strong>. Hal ini membuatnya mendapatkan perhatian dan persahabatan dari rajawali.",
               "Kisah ini mengingatkan kita untuk <strong>tidak menilai seseorang dari penampilan fisiknya, tetapi dari hati dan perbuatannya</strong>.",
          ].join(""),
          synopsis: [
               "Di sebuah desa, hidup bebek buruk rupa yang sering diolok-olok. Saat rajawali datang, semua hewan ingin mendapat perhatiannya. Meski kurang percaya diri, ia pun berteman dengan Rajawali karena kebaikan hatinya.",
          ].join(""),
     },
     {
          id: "fbojeo4yr6gnpwa7",
          title: "Si Kancil Pencuri Ketimun",
          category: "Fabel",
          origin: "Nusantara",
          imageId: "104",
          storyDesc: [
               "Di hutan belantara Nusantara, hiduplah seorang kancil cerdik dan lincah yang dikenal sebagai si Kancil. Kancil adalah hewan yang paling cerdik di hutan tersebut. Dia selalu pandai dalam menemukan cara untuk mengatasi masalah.",
               "\n \n",
               "Suatu hari, Kancil merasa sangat lapar. Dia berkeliling hutan untuk mencari makanan, namun dia tidak menemukan apa pun yang bisa dimakannya. Hingga akhirnya, dia melihat sebuah kebun ketimun milik seorang petani. Kebun tersebut dipenuhi dengan ketimun yang segar dan menggiurkan.",
               "\n \n",
               "Kancil merasa sangat senang melihat ketimun-ketimun itu. Namun, dia tahu bahwa dia tidak boleh memetik ketimun secara langsung karena takut akan tertangkap oleh petani. Oleh karena itu, dia harus mencari cara lain untuk mendapatkan ketimun itu tanpa ketahuan.",
               "\n \n",
               "Dengan cerdik, Kancil merencanakan sebuah trik. Dia memutuskan untuk meminta bantuan ular yang licik yang tinggal di dekat kebun ketimun. Kancil tahu bahwa ular tersebut memiliki kemampuan untuk masuk ke dalam kebun tanpa terlihat oleh petani.",
               "\n \n",
               "Kancil mendekati ular dan berkata, <em>\"Hai, saudaraku ular. Aku sangat lapar dan ingin sekali mendapatkan beberapa ketimun dari kebun petani. Bisakah kamu membantuku masuk ke dalam kebun tanpa ketahuan petani?\"</em>",
               "\n \n",
               "Ular yang serakah setuju untuk membantu Kancil, dengan imbalan sebagian dari hasil rampasannya. Tanpa diduga, Kancil dan ular berhasil masuk ke kebun dan mencuri banyak ketimun.",
               "\n \n",
               "Namun, ketika mereka hendak keluar dari kebun, petani melihat mereka. Petani marah besar dan mengejar mereka. Kancil yang cerdik segera melompat ke semak-semak dan berhasil lolos dari kejaran petani. Namun, ular yang lamban tertangkap oleh petani dan diusir dari kebun.",
               "\n \n",
               "Setelah berhasil lolos, Kancil merasa sangat senang dengan ketimun yang dia curi. Namun, dia juga merasa sedih karena ular telah menjadi korban karena keserakahannya. Dari pengalaman ini, Kancil belajar bahwa kecerdikan harus digunakan untuk hal-hal yang baik, bukan untuk mencuri atau menyakiti orang lain.",
               "\n \n",
               "Sejak saat itu, Kancil berjanji untuk tidak lagi mencuri atau memanfaatkan orang lain untuk keuntungannya sendiri. Dia menyadari bahwa tindakan egois seperti itu hanya akan merugikan dirinya sendiri dan orang lain di sekitarnya. Dia mulai bekerja keras untuk mendapatkan makanan dengan cara yang jujur dan tidak merugikan orang lain.",
               "\n \n",
               "Kancil kemudian menggunakan kecerdikannya untuk membantu hewan-hewan lain di hutan yang membutuhkan bantuan. Dia menjadi terkenal karena kebaikan hatinya dan menjadi teladan bagi hewan lain.",
          ].join(""),
          morals: [
               "Cerita ini mengajarkan kita bahwa <strong>kecerdikan harus digunakan untuk hal-hal yang baik dan positif</strong>. Meskipun Kancil berhasil mencuri ketimun dengan triknya, tindakan tersebut hanya menyebabkan kerugian bagi orang lain.",
               "Dari pengalaman ini, Kancil belajar bahwa egoisme dan kejahatan tidak akan membawa kebahagiaan jangka panjang. Sebaliknya, kita harus <strong>menggunakan kecerdikan kita untuk hal yang benar dan menguntungkan bersama</strong>.",
          ].join(""),
          synopsis: [
               "Kancil merasa lapar dan menemukan kebun ketimun. Ia pun meminta bantuan ular untuk mencurinya. Meski berhasil, ular tertangkap oleh petani. Kancil yang merasa bersalah bersumpah untuk tidak mencuri.",
          ].join(""),
     },
     {
          id: "sajql9fedywgacqj",
		title: "Prabu Siliwangi",
		category: "Sage",
		origin: "Jawa Barat",
          imageId: "200",
		storyDesc: [
               "Pada zaman dahulu, di tanah Sunda yang subur dan penuh dengan keindahan alam, berdirilah sebuah kerajaan besar bernama Pajajaran. Kerajaan ini dipimpin oleh seorang raja yang sangat bijaksana dan gagah perkasa, bernama Prabu Siliwangi. Beliau sangat dicintai oleh rakyatnya karena kebijaksanaannya, keberaniannya, dan keadilannya.",
               "\n \n",
               "Setiap pagi, Prabu Siliwangi selalu bangun dengan semangat baru. Setelah matahari terbit, ia akan berjalan-jalan di sekitar istana untuk menyapa rakyatnya. Pada suatu hari, saat Prabu Siliwangi sedang berjalan di pasar, ia melihat seorang petani tua yang sedang bersedih. Prabu Siliwangi mendekati petani itu dan bertanya, ",
               "\n",
               "<em>\"Wahai petani, kenapa kau terlihat begitu sedih?\"</em>",
               "\n \n",
               "Petani itu menghela napas panjang dan berkata",
               "\n",
               "<em>\"Yang Mulia, ladang kami telah dirusak oleh tikus-tikus. Kami takut tidak akan ada panen tahun ini, dan kami tidak akan bisa memberi makan keluarga kami.\"</em>",
               "\n \n",
               "Prabu Siliwangi berpikir sejenak, lalu tersenyum dan berkata, ",
               "\n",
               "<em>\"Jangan khawatir, aku punya ide. Kita akan memelihara kucing-kucing di ladangmu. Mereka akan menjaga ladangmu dari tikus-tikus itu.\"</em>",
               "\n \n",
               "Petani itu pun mengikuti saran Prabu Siliwangi. Beberapa hari kemudian, ladangnya kembali subur dan tikus-tikus tidak berani mendekat lagi. Petani itu sangat berterima kasih kepada raja yang bijaksana.",
               "\n \n",
               "Namun, kebijaksanaan bukanlah satu-satunya keunggulan Prabu Siliwangi. Beliau juga sangat pemberani. Suatu hari, terdengar kabar bahwa sebuah kerajaan tetangga berencana untuk menyerang Pajajaran. Raja musuh itu sangat jahat dan ingin merebut tanah Pajajaran yang subur.",
               "\n \n",
               "Prabu Siliwangi segera mengumpulkan pasukannya dan berkata, ",
               "\n",
               "<em>\"Kita harus melindungi tanah kita dan rakyat kita. Jangan biarkan musuh merusak kedamaian kita.\"</em>",
               "\n",
               "Dengan penuh semangat, prajurit Pajajaran bersiap-siap untuk berperang.",
               "\n \n",
               "Ketika pertempuran dimulai, Prabu Siliwangi berada di barisan terdepan, memimpin pasukannya dengan keberanian luar biasa. Ia melawan musuh dengan gagah berani dan memberi semangat kepada prajuritnya.",
               "\n",
               "<em>\"Kita harus menang! Untuk Pajajaran!\"</em> seru Prabu Siliwangi.",
               "\n \n",
               "Dengan keberanian dan strategi cerdas Prabu Siliwangi, pasukan Pajajaran berhasil mengalahkan musuh. Raja musuh melarikan diri, dan Pajajaran kembali aman. Rakyat bersorak gembira dan mengadakan pesta besar untuk merayakan kemenangan mereka.",
               "\n \n",
               "Rakyat Pajajaran sangat bersyukur memiliki raja seperti Prabu Siliwangi. Di bawah kepemimpinannya, kerajaan selalu dalam keadaan damai dan sejahtera. Prabu Siliwangi selalu memastikan bahwa setiap orang hidup dengan bahagia dan damai.",
          ].join(""),
          morals: [
               "Kisah Prabu Siliwangi mengajarkan nilai penting dari kepemimpinan yang <strong>bijak</strong>, <strong>berani</strong>, dan <strong>adil</strong>. Kisah juga ini menunjukkan bahwa pemimpin yang hebat adalah mereka yang memperhatikan kesejahteraan rakyatnya, berani menghadapi rintangan, dan cerdas dalam membuat keputusan.",
          ].join(""),
          synopsis: [
               "Prabu Siliwangi sang raja Pajajaran memperlihatkan kebaikan hatinya dengan membantu rakyat dan memperlihatkan keberaniannya ketika kerajaan tetangga menyerang.",
          ].join(""),
     },
     {
          id: "sgekvvogavmpgfme1",
		title: "Jaka Tingkir",
		category: "Sage",
		origin: "Jawa Tengah",
          imageId: "201",
		storyDesc: [
               "Pada zaman dahulu kala, di sebuah desa kecil di Jawa Tengah, hiduplah seorang pemuda yang bernama Jaka Tingkir. Jaka Tingkir adalah seorang pemuda yang gagah berani dan memiliki kekuatan yang luar biasa. Ia tinggal bersama ibunya di sebuah rumah sederhana. Walaupun hidup sederhana, Jaka Tingkir selalu bersemangat dan penuh kebaikan.",
               "\n \n",
               "Suatu hari, Jaka Tingkir memutuskan untuk pergi merantau ke kerajaan Pajang. Ia ingin mencari pengalaman dan belajar lebih banyak tentang kehidupan.",
               "Sebelum pergi, Jaka Tingkir berpamitan kepada ibunya, <em>\"Ibu, izinkan aku pergi merantau ke Pajang. Aku ingin mencari ilmu dan pengalaman yang lebih banyak.\"</em> kata Jaka Tingkir",
               "\n \n",
               "Ibunya memberikan restu dengan berat hati.",
               "\n",
               "<em>\"Hati-hati di jalan, anakku. Ingat selalu nasihat ibu dan jangan pernah lupa untuk berbuat baik,\"</em> pesan ibunya.",
               "\n \n",
               "Jaka Tingkir kemudian memulai perjalanannya. Di tengah perjalanan, ia harus melewati hutan yang lebat dan sungai yang deras. Namun, dengan keberaniannya, ia berhasil melewati semua rintangan tersebut. Akhirnya, Jaka Tingkir tiba di kerajaan Pajang.",
               "\n \n",
               "Di kerajaan Pajang, Jaka Tingkir mengabdi pada Sultan Hadiwijaya. Ia bekerja keras dan menunjukkan keberanian serta kesetiaannya. Suatu hari, terjadi kerusuhan di kerajaan. Seekor banteng besar mengamuk dan membuat kekacauan. Banyak prajurit kerajaan yang mencoba menaklukkan banteng tersebut, namun semuanya gagal.",
               "\n \n",
               "Mendengar hal itu, Jaka Tingkir menawarkan diri untuk menghadapi banteng yang mengamuk. Sultan Hadiwijaya mengizinkannya dengan harapan Jaka Tingkir bisa mengatasi masalah tersebut. Dengan penuh keberanian, Jaka Tingkir mendekati banteng yang besar dan ganas itu. Dengan kekuatannya yang luar biasa, ia berhasil menaklukkan banteng dan menenangkannya.",
               "\n",
               "Sultan Hadiwijaya sangat terkesan dengan keberanian dan kemampuan Jaka Tingkir. Sebagai tanda terima kasih, Sultan memberikan hadiah berupa jabatan penting di kerajaan. Jaka Tingkir kemudian diangkat menjadi seorang panglima yang bertanggung jawab atas keamanan kerajaan.",
               "\n",
               "Jaka Tingkir terus bekerja dengan rajin dan penuh dedikasi. Ia selalu berusaha melindungi kerajaan dari segala bahaya. Berkat keberaniannya, Jaka Tingkir menjadi sosok yang dihormati dan dikagumi oleh semua orang di kerajaan Pajang.",
               "\n \n",
               "Pada akhirnya, Jaka Tingkir tidak hanya dikenal sebagai pemuda yang gagah berani, tetapi juga sebagai pemimpin yang bijaksana. Ia selalu mengingat pesan ibunya untuk berbuat baik dan membantu sesama. Kehidupannya menjadi inspirasi bagi banyak orang.",
          ].join(""),
          morals: [
               "Cerita Jaka Tingkir mengajarkan kita tentang pentingnya <strong>keberanian</strong>, <strong>kerja keras</strong>, dan <strong>kesetiaan</strong>. Dengan sikap yang <strong>baik</strong> dan hati yang <strong>tulus</strong>, kita bisa mencapai hal-hal besar dan menjadi sosok yang dihormati serta dicintai oleh banyak orang.",
          ].join(""),
          synopsis: [
               "Jaka Tingkir merantau ke Pajang untuk mencari ilmu. Di sana, ia melawan seekor banteng yang sedang mengamuk. Karena keberaniannya ia menjadi sosok yang dihormati di kerajaan Pajang.",
          ].join(""),
     },
     {
          id: "sgcgfx5modassr6r",
		title: "Sangkuriang",
          category: "Sage",
          origin: "Jawa Barat",
          imageId: "202",
		storyDesc: [
               "Pada zaman dahulu kala, di sebuah kerajaan di Jawa Barat, hiduplah seorang putri yang sangat cantik dan cerdas bernama Dayang Sumbi. Dayang Sumbi tinggal di sebuah istana megah bersama ayahnya, sang raja. Namun, meskipun memiliki segala kemewahan, Dayang Sumbi merasa kesepian.",
               "\n \n",
               "Suatu hari, ketika sedang menenun, benang tenunannya jatuh ke lantai. Dayang Sumbi yang malas mengambilnya berkata",
               "\n",
               "<em>\"Siapa pun yang mengambilkan benangku, jika ia laki-laki akan menjadi suamiku, dan jika perempuan akan menjadi saudariku.\"</em>",
               "\n \n",
               "Tanpa disangka, seekor anjing bernama Tumang yang mengambilkan benang tersebut. Tumang sebenarnya adalah dewa yang dikutuk menjadi anjing. Karena sudah berjanji akhirnya Dayang Sumbi menikahi Tumang dan mereka memiliki seorang anak laki-laki yang diberi nama Sangkuriang. Sangkuriang tumbuh menjadi anak yang tangkas dan kuat. Namun, ia tidak mengetahui bahwa Tumang adalah ayahnya.",
               "\n \n",
               "Suatu hari, Dayang Sumbi menyuruh Sangkuriang pergi berburu dan meminta hati dari seekor kijang. Namun, Sangkuriang gagal mendapatkan kijang dan, karena takut mengecewakan ibunya, ia membunuh Tumang dan mengambil hatinya. Ketika Dayang Sumbi mengetahui kebenarannya, ia marah besar dan mengusir Sangkuriang.",
               "\n \n",
               "Bertahun-tahun kemudian, Sangkuriang yang sudah dewasa kembali ke desanya. Ia bertemu dengan Dayang Sumbi yang tetap terlihat muda dan cantik karena mendapatkan keabadian dari para dewa. Sangkuriang tidak mengenali ibunya sendiri dan jatuh cinta padanya. Mereka berencana untuk menikah.",
               "\n \n",
               "Namun suatu hari, Dayang Sumbi melihat bekas luka di kepala Sangkuriang yang membuatnya sadar bahwa pria itu adalah anaknya. Ia pun berusaha menghentikan pernikahan tersebut dengan memberikan syarat yang sangat sulit.",
               "\n",
               "<em>\"Aku akan menikah denganmu jika kamu bisa membuat danau dan sebuah perahu besar dalam semalam,\"</em> kata Dayang Sumbi.",
               "\n \n",
               "Dengan bantuan kekuatan gaibnya, Sangkuriang hampir menyelesaikan tugas tersebut. Dayang Sumbi yang khawatir akan berhasilnya Sangkuriang, meminta penduduk desa untuk membantunya dengan menumbuk padi dan menyalakan api besar di timur, membuat ayam berkokok lebih awal seolah-olah fajar sudah tiba.",
               "\n \n",
               "Sangkuriang merasa ditipu dan sangat marah. Dalam kemarahannya, ia menendang perahu yang hampir selesai itu hingga terbalik. Perahu tersebut berubah menjadi gunung yang kini dikenal sebagai Gunung Tangkuban Perahu, yang berarti 'perahu terbalik'.",
               "\n \n",
               "Gunung Tangkuban Perahu masih bisa dilihat hingga kini, mengingatkan kita akan kisah cinta dan tragedi antara Sangkuriang dan Dayang Sumbi.",
          ].join(""),
          morals: [
               "Cerita Sangkuriang mengajarkan kita tentang <strong>akibat dari ketidakjujuran</strong> dan <strong>pentingnya menghormati janji</strong>. Selain itu, cerita ini juga menunjukkan bahwa <strong>cinta dan nafsu harus disertai dengan pengetahuan dan kebijaksanaan</strong>, agar tidak membawa bencana.",
          ].join(""),
          synopsis: [
               "Pemuda sakti bernama Sangkuriang ingin menikahi Dayang Sumbi, ibu kandungnya. Dayang Sumbi mengajukan syarat agar Sangkuriang membangun perahu raksasa dalam satu malam.",
          ].join(""),
     },
     {
          id: "sgmwgycnzrho6evy",
          title: "Rawa Pening",
          category: "Sage",
          origin: "Jawa Tengah",
          imageId: "203",
		storyDesc: [
               "Pada zaman dahulu kala, di sebuah desa kecil di Jawa Tengah, hiduplah seorang anak kecil bernama Baru Klinthing. Baru Klinthing adalah seorang anak yang luar biasa. Ia sebenarnya adalah inkarnasi dari seekor naga yang memiliki kekuatan ajaib. Meskipun begitu, Baru Klinthing tumbuh seperti anak-anak lainnya di desa tersebut.",
               "\n \n",
               "Suatu hari, Baru Klinthing berjalan-jalan ke desa-desa sekitar untuk mencari makanan. Ia merasa sangat lapar dan berharap ada yang bersedia memberinya makan. Namun, semua penduduk desa menolak dan mengusirnya. Hanya seorang nenek tua yang merasa kasihan dan memberikan makanan kepada Baru Klinthing.",
               "\n",
               "<em>\"Terima kasih, Nek. Engkau sangat baik hati,\"</em> kata Baru Klinthing sambil makan dengan lahap.",
               "\n \n",
               "Setelah makan, Baru Klinthing memberikan pesan kepada nenek itu. <em>\"Nenek, tolong siapkan lesung di atas pohon. Sebentar lagi, desa ini akan tenggelam.\"</em> Nenek itu mengikuti saran Baru Klinthing tanpa bertanya lebih lanjut.",
               "\n \n",
               "Kemudian, Baru Klinthing kembali ke desa dan menancapkan sebatang lidi ke tanah. Ia menantang penduduk desa untuk mencabut lidi tersebut, tetapi tak seorang pun yang berhasil. Akhirnya, Baru Klinthing sendiri yang mencabut lidi itu.",
               "\n \n",
               "Begitu lidi tercabut, air memancar deras dari lubang yang ditinggalkan lidi tersebut. Air tersebut semakin lama semakin banyak dan menenggelamkan seluruh desa. Semua penduduk desa panik dan mencoba menyelamatkan diri, tetapi hanya nenek tua yang selamat karena ia mengikuti saran Baru Klinthing.",
               "\n \n",
               "Desa yang tenggelam tersebut akhirnya menjadi sebuah danau besar yang dikenal sebagai Rawa Pening. Danau itu masih ada hingga kini, sebagai pengingat akan cerita tentang Baru Klinthing dan kebijaksanaan nenek tua yang baik hati.",
               "\n \n",
               "Cerita ini mengajarkan kita tentang pentingnya bersikap baik kepada siapa pun, bahkan kepada orang yang tidak kita kenal. Kebaikan hati nenek tua tersebut menyelamatkan nyawanya, sementara penduduk desa yang lain mengalami nasib buruk karena keegoisan dan ketidakpedulian mereka.",
          ].join(""),
          morals: [
               "Cerita ini mengajarkan kita tentang pentingnya bersikap <strong>baik</strong> kepada siapa pun, bahkan kepada orang yang tidak kita kenal. Kebaikan hati nenek tua tersebut menyelamatkan nyawanya, sementara penduduk desa yang lain mengalami nasib buruk karena <strong>keegoisan</strong> dan <strong>ketidakpedulian</strong> mereka.",
          ].join(""),
          synopsis: [
               "Baru Klinthing yang merupakan inkarnasi naga merasa kelaparan, namun ketika seluruh desa menolaknya hanya seorang nenek yang membantunya. Karena ini sang nenek selamat saat bencana terjadi.",
          ].join(""),
     },
     {
          id: "sgbmtzlkh6joev6j",
          title: "Malin Kundang",
          category: "Sage",
          origin: "Sumatera Barat",
          imageId: "204",
		storyDesc: [
               "Pada zaman dahulu kala, di sebuah desa kecil di Sumatera Barat, hiduplah seorang pemuda bernama Malin Kundang. Malin Kundang adalah anak tunggal dari seorang janda miskin. Mereka hidup sangat sederhana, tetapi penuh kasih sayang dan kebahagiaan.",
               "\n \n",
               "Suatu hari, Malin Kundang memutuskan untuk merantau demi mencari peruntungan dan membantu ibunya keluar dari kemiskinan. Dengan berat hati, ibunya melepas kepergiannya.",
               "\n",
               "<em>\"Hati-hati di perjalanan, anakku. Ingat selalu nasihat ibu dan jangan pernah lupa untuk berbuat baik,\"</em> pesan ibunya.",
               "\n \n",
               "Malin Kundang kemudian memulai perjalanannya. Ia bekerja keras dan berjuang di negeri orang. Setelah bertahun-tahun, usaha Malin membuahkan hasil. Ia menjadi seorang pedagang kaya raya dan menikah dengan seorang wanita cantik dari keluarga bangsawan.",
               "\n \n",
               "Suatu hari, Malin Kundang memutuskan untuk pulang ke desanya dengan kapal besar dan mewah. Ketika mendengar kabar bahwa Malin Kundang telah kembali, ibunya sangat gembira dan bergegas menyambutnya di pelabuhan. Namun, alangkah terkejutnya sang ibu ketika Malin Kundang tidak mengenalinya dan malah mengusirnya.",
               "\n \n",
               "Malin Kundang merasa malu mengakui ibunya yang berpakaian lusuh di hadapan istri dan awak kapalnya. Dengan hati hancur, sang ibu berdoa kepada Tuhan,",
               "\n",
               "<em>\"Ya Tuhan, jika benar dia anakku, kutuklah dia menjadi batu jika ia benar-benar durhaka.\"</em>",
               "\n \n",
               "Tak lama setelah itu, langit mendadak gelap dan badai besar melanda. Kapal Malin Kundang hancur diterjang ombak. Malin Kundang yang menyesali perbuatannya, perlahan berubah menjadi batu. Batu tersebut masih bisa dilihat di pantai Air Manis hingga kini, menyerupai sosok manusia yang sedang bersujud.",
          ].join(""),
          morals: [
               "Cerita Malin Kundang mengajarkan kita tentang <strong>pentingnya berbakti kepada orang tua</strong> dan <strong>menghargai asal-usul kita</strong>. Kisah ini juga memperingatkan kita tentang <strong>akibat dari kesombongan dan ketidaksetiaan</strong> terhadap keluarga.",
          ].join(""),
          synopsis: [
               "Malin Kundang yang pulang dari merantau lupa diri karena harta sampai mengusir ibunya yang miskin. Sang ibu yang terluka pun mengutuknya menjadi batu.",
          ].join(""),
     },
     {
		id: "lgchskjbp_lsnwms",
		title: "Legenda Danau Toba dan Pulau Samosir",
		category: "Legenda",
		origin: "Sumatra Utara",
          imageId: "300",
		storyDesc: [
               "Pada suatu waktu yang sangat lama, di sebuah desa kecil yang dikelilingi oleh gunung-gunung hijau, hiduplah seorang pemuda bernama Toba. Toba adalah seorang petani yang rajin dan baik hati. Setiap hari, Toba bekerja di ladangnya, menanam padi dan sayuran.",
               "\n \n",
               "Suatu hari, saat Toba sedang memancing di sungai yang jernih, dia menangkap ikan yang sangat besar dan indah. Ikan itu berwarna keemasan dan berkilauan di bawah sinar matahari. Toba sangat senang dan membawa ikan itu pulang untuk dimasak.",
               "\n \n",
               "Namun, saat Toba hendak memasak ikan itu, tiba-tiba ikan tersebut berubah menjadi seorang gadis cantik.",
               "\n",
               "Toba terkejut dan bertanya, <em>\"Siapa kamu?\"</em>",
               "\n \n",
               "Gadis itu menjawab, \"Aku adalah putri dari kerajaan ikan. Karena kebaikan hatimu, aku diizinkan untuk menjadi manusia. Tapi ada satu syarat, kamu tidak boleh memberitahukan siapa pun tentang asal usulku sebagai ikan.\"",
               "\n \n",
               "Toba setuju dan mereka menikah. Mereka hidup bahagia dan memiliki seorang anak laki-laki bernama Samosir. Samosir adalah anak yang cerdas dan aktif, tetapi dia juga sangat nakal dan suka makan banyak.",
               "\n \n",
               "Suatu hari, Toba marah besar karena Samosir menghabiskan semua makanan di rumah. Dalam kemarahannya,",
               "\n",
               "Toba lupa akan janjinya dan berkata, <em>\"Dasar anak ikan!\"</em>",
               "\n \n",
               "Seketika itu juga, langit menjadi gelap dan petir menyambar. Istri Toba yang mendengar kata-kata itu merasa sangat sedih.",
               "\n",
               "Dia berkata, <em>\"Toba, kamu telah melanggar janjimu. Sekarang aku harus kembali ke asal usulku.\"</em>",
               "\n \n",
               "Istri Toba segera berubah kembali menjadi ikan dan melompat ke sungai. Air sungai itu kemudian meluap dan membanjiri seluruh desa. Toba dan Samosir berlari ke tempat yang tinggi untuk menyelamatkan diri.",
               "\n \n",
               "Banjir itu tidak berhenti dan terus meluas hingga membentuk sebuah danau besar yang sekarang dikenal sebagai Danau Toba. Di tengah danau itu, ada sebuah pulau yang dinamai sesuai dengan nama anak mereka, Pulau Samosir.",
          ].join(""),
          morals: [
               "Kisah Legenda Danau Toba menyampaikan pesan moral yang kuat tentang pentingnya memegang janji dan menghargai orang lain. Toba, yang melanggar janjinya kepada istrinya, akhirnya menghadapi konsekuensi tragis yang tidak hanya menimpa dirinya tetapi juga seluruh desanya.",
               "\n",
               "Cerita ini mengajarkan bahwa setiap janji harus dihormati dan dipatuhi, karena pelanggaran terhadap janji bisa membawa dampak buruk yang tidak terduga. Selain itu, legenda ini juga menekankan nilai-nilai seperti <strong>kesetiaan</strong>, <strong>kejujuran</strong>, dan <strong>tanggung jawab</strong> dalam hubungan antar sesama.",
               "\n",
               "Melalui kisah ini, kita diajak untuk selalu berhati-hati dengan kata-kata dan tindakan kita, serta untuk menghormati komitmen yang telah kita buat kepada orang lain.",
          ].join(""),
          synopsis: [
               "Toba menemukan ikan emas yang berubah menjadi gadis cantik. Mereka menikah dan memiliki anak bernama Samosir. Namun, sebuah kesalahan yang Toba lakukan membawa bencana ke desanya.",
          ].join(""),
	},
     {
          id: "lgyeombqti07yugo",
		title: "Legenda Gunung Merapi",
		category: "Legenda",
		origin: "Jawa Tengah",
          imageId: "301",
		storyDesc: [
               "Pada zaman dahulu kala, di tanah Jawa yang subur, hiduplah seorang raja yang bijaksana bernama Prabu Siliwangi. Kerajaannya sangat makmur dan rakyatnya hidup damai dan bahagia. Namun, di dekat kerajaan tersebut, ada sebuah gunung besar yang sangat terkenal, yaitu Gunung Merapi.",
               "\n \n",
               "Gunung Merapi adalah gunung yang sangat kuat dan perkasa. Di dalam gunung ini, konon katanya, terdapat sebuah kerajaan makhluk halus yang dipimpin oleh Raja Mahesa Sura dan Patih Mahesa Sura. Mereka adalah makhluk yang kuat dan berkuasa.",
               "\n \n",
               "Suatu hari, Raja Mahesa Sura dan Patih Mahesa Sura merasa bosan di dalam gunung dan ingin melihat dunia luar. Mereka mendaki keluar dari dalam gunung dan melihat betapa indahnya dunia di luar. Mereka sangat kagum dengan keindahan alam dan kehidupan di sekitar mereka.",
               "\n \n",
               "Ketika mereka turun dari gunung, mereka bertemu dengan seorang petani tua yang sedang bekerja di ladangnya. Petani tua itu sangat ramah dan menyambut mereka dengan baik. Raja Mahesa Sura dan Patih Mahesa Sura merasa senang dan memutuskan untuk tinggal di desa tersebut untuk beberapa waktu.",
               "\n \n",
               "Namun, kedatangan mereka ternyata membawa masalah. Gunung Merapi mulai menunjukkan tanda-tanda akan meletus. Asap tebal dan abu vulkanik mulai keluar dari puncak gunung, dan warga desa mulai khawatir. Mereka tahu bahwa letusan Gunung Merapi bisa sangat berbahaya.",
               "\n \n",
               "Prabu Siliwangi mendengar kabar tentang gunung yang akan meletus dan segera memutuskan untuk mencari tahu penyebabnya. Dia naik ke puncak Gunung Merapi dan bertemu dengan Raja Mahesa Sura dan Patih Mahesa Sura.",
               "\n",
               "<em>\"Wahai Mahesa Sura dan Patih Mahesa Sura, mengapa Gunung Merapi akan meletus?\"</em> tanya Prabu Siliwangi.",
               "\n \n",
               "Raja Mahesa Sura menjawab, <em>\"Kami merasa bosan di dalam gunung dan ingin melihat dunia luar. Tapi kami tidak menyangka bahwa kehadiran kami akan menyebabkan gunung ini meletus.\"</em>",
               "\n \n",
               "Prabu Siliwangi berpikir sejenak, lalu berkata, <em>\"Kalian harus kembali ke dalam gunung untuk menjaga keseimbangan alam. Jika tidak, letusan gunung ini akan sangat berbahaya bagi semua orang.\"</em>",
               "\n \n",
               "Raja Mahesa Sura dan Patih Mahesa Sura mengerti dan setuju untuk kembali ke dalam gunung. Mereka berjanji untuk menjaga Gunung Merapi agar tetap tenang dan tidak meletus. Sebagai tanda persahabatan, mereka memberikan hadiah berupa harta karun yang sangat berharga kepada Prabu Siliwangi.",
               "\n \n",
               "Sejak saat itu, Gunung Merapi tetap tenang dan tidak meletus. Namun, warga desa selalu waspada dan menjaga gunung dengan baik, serta menghormati makhluk halus yang tinggal di dalamnya.",
          ].join(""),
          morals: [
               "Legenda Gunung Merapi mengajarkan tentang pentingnya <strong>menjaga keseimbangan dan keharmonisan dengan alam</strong>, <strong>menghormati kekuatan alam</strong>, serta hidup dengan <strong>rendah hati</strong> dan <strong>penuh kesadaran akan bahaya bencana alam</strong>",
               "\n",
               "Kisah ini juga menekankan pentingnya <strong>kearifan lokal dan tradisi</strong> dalam menjaga <strong>keselamatan dan kesejahteraan masyarakat</strong>.",
          ].join(""),
          synopsis: [
               "Di tanah Jawa yang damai tedapat Gunung Merapi yang perkasa. Namun, kedamaian terganggu saat Raja Mahesa Sura dan Patihnya meninggalkan gunung dan memicu letusan.",
          ].join(""),
     },
     {
          id: "lg4ghbii7iiwtoti",
		title: "Legenda Situ Bagendit",
		category: "Legenda",
		origin: "Jawa Barat",
          imageId: "302",
		storyDesc: [
               "Pada zaman dahulu kala, di sebuah desa di Garut, Jawa Barat, hiduplah seorang wanita kaya bernama Nyai Endit. Nyai Endit memiliki banyak harta, ladang yang luas, dan rumah yang besar. Namun, meskipun sangat kaya, Nyai Endit adalah orang yang sangat pelit dan tidak mau berbagi dengan orang lain.",
               "\n \n",
               "Setiap hari, banyak penduduk desa yang datang ke rumah Nyai Endit untuk meminta bantuan, tetapi Nyai Endit selalu menolak mereka dengan kasar. Dia lebih memilih menyimpan semua hartanya untuk dirinya sendiri.",
               "\n \n",
               "Suatu hari, datanglah seorang kakek tua yang berpakaian lusuh ke rumah Nyai Endit. Kakek itu meminta sedikit air karena sangat haus.",
               "\n",
               "<em>\"Nyai Endit, bisakah kau memberiku sedikit air untuk minum? Aku sangat haus,\"</em> kata kakek tua itu dengan suara lemah.",
               "\n \n",
               "Namun, Nyai Endit malah marah dan mengusir kakek tua itu. <em>\"Pergi dari sini! Aku tidak punya air untukmu. Cari saja di tempat lain!\"</em> seru Nyai Endit dengan suara keras.",
               "\n \n",
               "Kakek tua itu merasa sangat sedih dan pergi dari rumah Nyai Endit.",
               "\n",
               "Tapi sebelum pergi, dia mengucapkan sebuah kutukan, <em>\"Nyai Endit, karena keserakahan dan kekejamanmu, kau akan menerima hukuman yang setimpal.\"</em>",
               "\n \n",
               "Setelah kakek tua itu pergi, langit yang tadinya cerah tiba-tiba menjadi gelap. Awan hitam berkumpul di langit, dan hujan turun dengan sangat deras. Hujan tidak berhenti-henti, dan air mulai menggenangi desa.",
               "\n \n",
               "Nyai Endit tidak menyadari bahaya yang mengancam. Dia tetap duduk di rumahnya dengan semua harta kekayaannya. Namun, air semakin naik dan mulai masuk ke dalam rumahnya. Nyai Endit panik dan berusaha menyelamatkan hartanya, tetapi air terus naik dengan cepat.",
               "\n \n",
               "Tidak lama kemudian, seluruh desa terendam air, termasuk rumah Nyai Endit. Nyai Endit dan semua hartanya tenggelam dalam air yang sangat deras. Desa itu berubah menjadi sebuah danau yang besar, yang sekarang dikenal sebagai Situ Bagendit.",
               "\n \n",
               "Penduduk desa yang selamat dari banjir merasa bersyukur karena mereka terbebas dari kekejaman Nyai Endit. Mereka percaya bahwa danau itu adalah tanda dari Tuhan untuk mengingatkan manusia agar tidak serakah dan harus berbagi dengan sesama.",
          ].join(""),
          morals: [
               "Legenda Situ Bagendit ini mengajarkan kita untuk <strong>selalu berbagi</strong> dan <strong>tidak menjadi orang yang pelit atau serakah</strong>. Kita harus selalu <strong>peduli</strong> dan <strong>membantu sesama</strong> yang membutuhkan.",
          ].join(""),
          synopsis: [
               "Seorang wanita kaya yang pelit bernama Nyai Endit menolak berbagi harta dengan siapapun. Karena keserakahannya seorang kakek mengutuknya dan menghancurkan segalanya.",
          ].join(""),
     },
     {
          id: "lgbirorjar2n5teq",
		title: "Legenda Si Joko Kendil",
		category: "Legenda",
		origin: "Jawa Tengah",
          imageId: "303",
		storyDesc: [
               "Pada zaman dahulu kala, di sebuah desa yang damai dan subur, hiduplah seorang anak laki-laki yang aneh bernama Joko Kendil. Dia disebut Joko Kendil karena tubuhnya kecil dan bundar seperti kendil, sebuah periuk tanah liat.",
               "\n \n",
               "Joko Kendil tinggal bersama ibunya yang sangat mencintainya. Meskipun tubuhnya kecil dan bundar, Joko Kendil adalah anak yang cerdas dan baik hati. Sayangnya, penduduk desa sering mengejeknya karena penampilannya yang tidak biasa.",
               "\n",
               "Suatu hari, Joko Kendil berkata kepada ibunya, <em>\"Bu, aku ingin pergi berkelana dan mencari pengalaman baru.\"</em> ",
               "\n \n",
               "Ibunya awalnya khawatir, tetapi dia tahu bahwa Joko Kendil memiliki hati yang kuat dan penuh tekad.",
               "\n \n",
               "Dengan membawa bekal sederhana, Joko Kendil berangkat. Dalam perjalanan, dia bertemu dengan banyak orang dan membantu mereka dengan kebijaksanaan dan kebaikan hatinya. Meskipun tubuhnya kecil, Joko Kendil memiliki akal yang cerdik dan selalu menemukan cara untuk menyelesaikan masalah.",
               "\n \n",
               "Suatu hari, Joko Kendil tiba di sebuah kerajaan yang sedang bersedih. Ternyata, sang raja memiliki tiga putri yang sangat cantik, tetapi putri bungsu, Putri Endah, tidak pernah tersenyum karena merasa sedih dan kesepian.",
               "\n \n",
               "Raja mengumumkan bahwa siapa saja yang bisa membuat Putri Endah tersenyum akan diberikan hadiah besar. Joko Kendil merasa kasihan kepada Putri Endah dan bertekad untuk mencoba. Dia pergi ke istana dan meminta izin untuk bertemu dengan sang putri.",
               "\n \n",
               "Ketika Joko Kendil berdiri di depan Putri Endah, dia mulai bercerita tentang petualangannya yang lucu dan menarik. Dia menceritakan bagaimana dia membantu orang-orang dengan cara yang unik dan cerdik. Putri Endah mendengarkan dengan penuh perhatian, dan tiba-tiba, senyuman muncul di wajahnya. Dia tertawa riang mendengar cerita-cerita Joko Kendil yang kocak.",
               "\n \n",
               "Raja sangat gembira melihat Putri Endah tersenyum dan memeluk Joko Kendil dengan bahagia. ",
               "\n",
               "\"Kau telah membuat putriku tersenyum! Aku sangat berterima kasih padamu, Joko Kendil,\"</em> kata sang raja.",
               "\n \n",
               "Sebagai hadiah, raja menawarkan Joko Kendil emas, perak, dan permata. ",
               "\n",
               "Tetapi Joko Kendil menolak dengan sopan. <em>\"Terima kasih, Yang Mulia. Saya tidak membutuhkan harta. Saya hanya ingin melihat orang lain bahagia.\"</em>",
               "\n \n",
               "Raja dan seluruh kerajaan sangat terkesan dengan kebaikan hati Joko Kendil. Mereka mengadakan pesta besar untuk merayakan kebahagiaan Putri Endah dan kebaikan Joko Kendil. Putri Endah dan Joko Kendil menjadi sahabat baik dan sering berbagi cerita dan tawa bersama.",
          ].join(""),
          morals: [
               "Kisah Si Joko Kendil mengajarkan kita bahwa <strong>kebaikan hati</strong> dan <strong>kebijaksanaan</strong> adalah <strong>harta yang paling berharga</strong>. Jangan pernah menilai seseorang dari penampilannya, tetapi <strong>lihatlah hatinya yang baik dan cerdas</strong>.",
               "\n",
               "Kebaikan yang kita berikan kepada orang lain akan membawa kebahagiaan bagi semua.",
          ].join(""),
          synopsis: [
               "Joko Kendil memiliki tubuh kecil seperti kendil. Meski sering diejek, ia tetap menjadi anak yang baik. Karena kebaikan ini keberuntungan datang kepadanya.",
          ].join(""),
     },
     {
          id: "lgajekw1qof8uegt",
		title: "Legenda Banyuwangi",
		category: "Legenda",
		origin: "Jawa Timur",
          imageId: "304",
		storyDesc: [
               "Dahulu kala, di sebuah kerajaan yang damai di Jawa Timur, hiduplah seorang raja yang bijaksana bersama putri cantiknya yang bernama Putri Sri Tanjung. Putri Sri Tanjung terkenal tidak hanya karena kecantikannya, tetapi juga karena hatinya yang baik dan lembut.",
               "\n \n",
               "Suatu hari, seorang pangeran dari kerajaan tetangga yang bernama Raden Sidapaksa datang ke kerajaan itu. Raden Sidapaksa jatuh cinta pada Putri Sri Tanjung pada pandangan pertama dan akhirnya mereka menikah. Mereka hidup bahagia dan saling mencintai.",
               "\n \n",
               "Namun, kebahagiaan mereka tidak berlangsung lama. Suatu hari, Raden Sidapaksa harus pergi berperang untuk membela kerajaannya. Sebelum pergi, dia meninggalkan Putri Sri Tanjung dengan berat hati, berjanji akan kembali secepat mungkin.",
               "\n \n",
               "Setelah beberapa bulan, Raden Sidapaksa kembali dari peperangan. Namun, seorang menteri jahat yang iri pada kebahagiaan mereka memfitnah Putri Sri Tanjung. Dia mengatakan kepada Raden Sidapaksa bahwa Putri Sri Tanjung tidak setia selama Raden Sidapaksa pergi.",
               "\n \n",
               "Raden Sidapaksa sangat marah mendengar tuduhan itu. Tanpa bertanya terlebih dahulu pada Putri Sri Tanjung, dia langsung mempercayai fitnah tersebut.",
               "\n",
               "<em>\"Aku tidak menyangka kau bisa melakukan ini, Sri Tanjung,\"</em> kata Raden Sidapaksa dengan marah.",
               "\n \n",
               "Putri Sri Tanjung terkejut dan sedih mendengar tuduhan suaminya.",
               "\n \n",
               "<em>\"Aku tidak pernah mengkhianatimu, Raden Sidapaksa. Aku setia padamu,\"</em> kata Putri Sri Tanjung sambil menangis.",
               "\n \n",
               "Namun, Raden Sidapaksa tidak mau mendengarkan. Dia membawa Putri Sri Tanjung ke tepi sungai dan berniat membunuhnya. Sebelum Raden Sidapaksa melakukan niat jahatnya, Putri Sri Tanjung berdoa kepada Tuhan.",
               "\n",
               "<em>\"Ya Tuhan, jika aku benar-benar setia, buktikanlah dengan air sungai ini menjadi jernih dan berbau harum,\"</em> doanya.",
               "\n \n",
               "Setelah itu, Raden Sidapaksa mendorong Putri Sri Tanjung ke dalam sungai. Ajaibnya, air sungai yang tadinya keruh berubah menjadi jernih dan mengeluarkan aroma harum. Raden Sidapaksa terkejut dan menyadari bahwa Putri Sri Tanjung memang setia.",
               "\n",
               "<em>\"Ini pasti pertanda bahwa kau tidak bersalah, Sri Tanjung. Maafkan aku,\"</em> kata Raden Sidapaksa sambil menangis.",
               "\n \n",
               "Sejak saat itu, sungai tersebut dikenal sebagai <strong>'Banyuwangi'</strong> yang berarti 'air yang harum'. Nama ini diberikan untuk mengenang kesetiaan dan kesucian Putri Sri Tanjung.",
          ].join(""),
          morals: [
               "Legenda Banyuwangi mengajarkan kita betapa pentingnya <strong>kesetiaan</strong>,<strong> kejujuran</strong>, dan <strong>keadilan</strong> yang menunjukkan bahwa ketidakpercayaan tanpa dasar dapat merusak hubungan dan membawa penyesalan. ",
               "\n",
               "Selain itu, <strong>doa</strong> dan <strong>kepercayaan pada Tuhan Yang Maha Esa</strong> dalam menghadapi situasi sulit juga menjadi nilai penting yang diajarkan oleh kisah ini.",
          ].join(""),
          synopsis: [
               "Putri Sri Tanjung menikah dengan Raden Sidapaksa dan hidup bahagia. Namun, kebahagiaan mereka terganggu ketika sang Putri difitnah oleh seorang menteri jahat.",
          ].join(""),
     },
	{
		id: "dgkemnmpb_prty8f",
		title: "Cinderalas",
		category: "Dongeng",
		origin: "Jawa Timur",
          imageId: "400",
		storyDesc: [
               "Pada suatu masa di kerajaan Jenggala, hiduplah seorang raja yang bijaksana bernama Raden Putra. Sang raja memiliki seorang permaisuri yang cantik dan baik hati. Namun, kebahagiaan mereka terusik oleh perbuatan jahat seorang selir yang iri hati. Selir tersebut ingin menjadi satu-satunya istri raja dan merencanakan sebuah fitnah untuk menjatuhkan permaisuri. Ia bersekongkol dengan tabib istana untuk memfitnah permaisuri dengan tuduhan bahwa permaisuri telah meracuni raja.",
               "\n \n",
               "Tabib yang licik itu pura-pura memeriksa kesehatan raja dan menyatakan bahwa raja telah diracuni oleh permaisuri. Mendengar kabar itu, Raden Putra sangat marah dan sedih. Tanpa penyelidikan lebih lanjut, ia memerintahkan agar permaisuri dibuang ke hutan belantara. Prajurit yang bertugas mengusir permaisuri merasa iba, tetapi ia tidak bisa melawan perintah raja. Di tengah hutan, permaisuri ditinggalkan sendirian. Tak lama setelah ditinggalkan, permaisuri melahirkan seorang bayi laki-laki yang diberi nama Cindelaras.",
               "\n \n",
               "Cindelaras tumbuh menjadi anak yang kuat dan cerdas di tengah hutan. Ia dibesarkan oleh ibunya dengan penuh kasih sayang. Pada suatu hari, seekor ayam jantan muncul dan menjadi sahabat Cindelaras. Ayam tersebut bukan ayam biasa, melainkan ayam ajaib yang bisa berbicara. Suatu pagi, ayam itu berkata kepada Cindelaras,",
               "\n",
               "<em>\"Majikanku adalah Cindelaras, rumahnya di tengah hutan, anak Raden Putra.\"</em>",
               "\n",
               "Mendengar hal itu, Cindelaras terkejut dan menanyakan lebih lanjut kepada ibunya. Akhirnya, ibunya menceritakan asal-usul mereka yang sebenarnya.",
               "\n \n",
               "Cindelaras merasa terpanggil untuk mencari kebenaran dan menuntut keadilan. Bersama ayam jantannya, ia memutuskan pergi ke istana Jenggala. Dalam perjalanan menuju istana, keajaiban ayam Cindelaras menyebar ke seluruh negeri. Banyak orang yang kagum dengan ayam tersebut, karena selain bisa berbicara, ayam itu juga sangat kuat dan selalu menang dalam setiap pertarungan ayam. Berita tentang ayam ajaib ini akhirnya sampai ke telinga Raden Putra.",
               "\n \n",
               "Raden Putra yang penasaran mengundang Cindelaras untuk datang ke istana dan mengadu ayam jantannya. Setibanya di istana, Cindelaras langsung dipertemukan dengan raja. Raja menantang Cindelaras untuk mengadu ayamnya dengan ayam kerajaan. Dengan tenang, Cindelaras menerima tantangan itu. Dalam pertarungan tersebut, ayam Cindelaras dengan mudah mengalahkan ayam kerajaan. Raden Putra merasa takjub dan penasaran dengan pemuda ini.",
               "\n",
               "Setelah pertandingan, ayam Cindelaras kembali berbicara, <em>\"Majikanku adalah Cindelaras, rumahnya di tengah hutan, anak Raden Putra.\"</em>",
               "\n",
               "Raja terkejut dan meminta Cindelaras untuk menceritakan lebih lanjut. Cindelaras pun menceritakan kisah hidupnya serta fitnah yang menimpa ibunya. Mendengar cerita itu, Raden Putra tersentak dan menyadari kesalahannya. Ia segera memanggil prajurit yang dulu mengusir permaisuri dan meminta mereka menjemputnya kembali.",
               "\n \n",
               "Permaisuri yang telah lama hidup di hutan akhirnya dibawa kembali ke istana. Raden Putra meminta maaf kepada permaisuri dan Cindelaras atas kesalahpahaman yang telah terjadi. Ia juga menghukum selir yang licik dan tabib yang telah memfitnah permaisuri. Keadilan pun ditegakkan di kerajaan Jenggala. ",
               "\n \n",
               "Raden Putra sangat bangga dengan keberanian dan keteguhan hati Cindelaras. Ia mengangkat Cindelaras sebagai putra mahkota. Cindelaras tumbuh menjadi pemuda yang bijaksana dan siap untuk memimpin kerajaan di masa depan. Kisah Cindelaras menjadi inspirasi bagi rakyat Jenggala tentang pentingnya kejujuran dan kebenaran.",
               "\n \n",
               "Kerajaan Jenggala pun kembali damai dan sejahtera. Cindelaras bersama ayam ajaibnya menjadi legenda yang diceritakan dari generasi ke generasi. Mereka diingat sebagai simbol keadilan dan keberanian yang abadi dalam hati masyarakat.",
          ].join(""),
          morals: [
               "Kisah Cinderalas mengandung beberapa pesan moral penting, di antaranya bahwa kebenaran akan selalu terungkap meskipun butuh waktu. <strong>Kesabaran</strong> dan <strong>keteguhan</strong> hati permaisuri saat diasingkan, serta <strong>kebaikan</strong> dan <strong>kebijaksanaan</strong> yang diajarkan kepada Cinderalas, menunjukkan bahwa nilai-nilai positif ini akan mendapatkan balasan yang baik",
               "\n",
               "<strong>Kejujuran</strong> dan <strong>keberanian</strong> Cinderalas dalam menghadapi tantangan, serta keadilan yang akhirnya ditegakkan oleh Raja Raden Putra, mengajarkan bahwa kebenaran dan keadilan akan menang pada akhirnya.",
               "\n",
          ].join(""),
          synopsis: [
               "Cindelaras dibesarkan oleh ibunya, sang ibu adalah permaisuri yang dituduh meracuni raja dan diusir dari istana. Dengan ditemani ayam ajaib, Cindelaras memulai perjalanan mencari keadilan.",
          ].join(""),
	},
     {
          id: "dg13ng069jgjqbor",
		title: "Bawang Merah dan Bawang Putih",
		category: "Dongeng",
		origin: "Sumatra",
          imageId: "401",
          storyDesc: [
               "Pada suatu waktu di desa yang jauh, hiduplah seorang gadis baik hati bernama Bawang Putih. Dia tinggal bersama ayahnya dan ibu tirinya yang sangat jahat serta saudara tirinya yang bernama Bawang Merah. Bawang Merah dan ibunya selalu membuat Bawang Putih bekerja keras, sementara mereka bermalas-malasan.",
               "\n \n",
               "Setiap hari, Bawang Putih harus membersihkan rumah, memasak, dan mengerjakan semua pekerjaan berat. Meskipun demikian, dia selalu sabar dan tidak pernah mengeluh. Sementara itu, Bawang Merah hanya duduk-duduk dan menikmati hidupnya tanpa peduli akan Bawang Putih.",
               "\n \n",
               "Suatu hari, Bawang Putih pergi ke sungai untuk mencuci pakaian. Saat sedang mencuci, tiba-tiba sebuah baju milik ibu tirinya hanyut terbawa arus. Bawang Putih panik dan mengikuti arus sungai untuk mencari baju tersebut. Di tengah pencariannya, dia bertemu dengan seorang nenek tua yang baik hati.",
               "\n",
               "Nenek tua itu bertanya, <em>\"Mengapa kamu terlihat sedih, nak?\"</em>",
               "\n\n",
               "Bawang Putih menjawab, <em>\"Baju ibu tiri saya hanyut ke sungai, dan saya tidak bisa menemukannya. Saya takut ibu tiri saya akan marah.\"</em>",
               "\n\n",
               "Nenek itu tersenyum dan berkata, <em>\"Jangan khawatir, nak. Aku akan membantumu. Tapi, tolong bantu aku terlebih dahulu dengan pekerjaan rumahku.\"</em>",
               "\n\n",
               "Bawang Putih setuju dan membantu nenek tua itu dengan senang hati. Setelah selesai, nenek itu memberikan dua labu: satu labu kecil dan satu labu besar.",
               "\n",
               "<em>\"Pilihlah satu labu ini sebagai hadiah untukmu,\"</em> kata nenek itu.",
               "\n \n",
               "Bawang Putih memilih labu kecil karena dia merasa sudah cukup terbantu oleh nenek tersebut. Setelah mengucapkan terima kasih, Bawang Putih pulang ke rumah dengan labu kecil itu.",
               "\n \n",
               "Setibanya di rumah, Bawang Putih membuka labu tersebut dan alangkah terkejutnya dia saat menemukan labu itu penuh dengan emas dan permata. Ibu tiri dan Bawang Merah yang melihat hal ini menjadi sangat iri dan mereka merencanakan sesuatu.",
               "\n \n",
               "Keesokan harinya, Bawang Merah berpura-pura mencuci pakaian di sungai dan dengan sengaja membiarkan bajunya hanyut. Dia mengikuti alur cerita Bawang Putih dan bertemu dengan nenek tua yang sama. Namun, Bawang Merah tidak sabar dan kasar saat membantu nenek itu.",
               "\n \n",
               "Meskipun demikian, nenek tua itu tetap memberikan dua labu dan meminta Bawang Merah memilih satu. Karena serakah, Bawang Merah memilih labu yang besar dan segera membawanya pulang.",
               "\n \n",
               "Setibanya di rumah, Bawang Merah dan ibunya membuka labu besar itu dengan penuh semangat. Namun, bukannya emas dan permata, keluar banyak ular dan binatang berbisa dari dalam labu. Ibu tiri dan Bawang Merah sangat ketakutan dan menyesali keserakahan serta kejahatan mereka.",
               "\n \n",
               "Akhirnya, ibu tiri dan Bawang Merah meminta maaf kepada Bawang Putih. Mereka berjanji untuk tidak bersikap jahat lagi. Sejak saat itu, mereka hidup bersama dengan damai dan saling membantu.",
          ].join(""),
          morals: [
               "Dongeng Bawang Putih dan Bawang Merah mengajarkan bahwa <strong>kebaikan hati</strong> dan <strong>esabaran</strong> akan selalu mendapatkan balasan yang baik, sementara <strong>keserakahan</strong> dan <strong>kejahatan</strong> hanya akan membawa penderitaan. Jadi, mari kita selalu bersikap baik dan membantu antar sesama.",
          ].join(""),
          synopsis: [
               "Bawang Putih tinggal bersama keluarganya. Meski selalu diperlakukan tidak adil, ia tetap sabar. Suatu hari, seorang nenek tua merubah kehidupannya bersama keluarga.",
          ].join(""),
     },
     {
          id: "dgmwb4kgkp3bblu9",
		title: "Keong Emas",
		category: "Dongeng",
		origin: "Jawa Tengah",
          imageId: "402",
          storyDesc: [
               "Pada zaman dahulu kala, di sebuah kerajaan yang damai, hiduplah seorang putri cantik bernama Candra Kirana. Candra Kirana tinggal di istana bersama ayahnya, Raja Kertamarta, dan kakaknya, Dewi Galuh. Meskipun hidup di istana yang megah, Candra Kirana selalu bersikap baik hati dan ramah kepada semua orang.",
               "\n \n",
               "Suatu hari, seorang penyihir jahat yang iri kepada Candra Kirana menyihirnya menjadi seekor keong emas. Penyihir itu ingin mengusir Candra Kirana dari istana agar Dewi Galuh, yang diam-diam juga iri kepada adiknya, bisa menjadi putri paling cantik di kerajaan. Dengan kesedihan mendalam, Candra Kirana berubah menjadi keong emas dan terdampar di sebuah sungai yang jauh dari istana.",
               "\n \n",
               "Di sungai itu, seorang nenek tua yang baik hati menemukan keong emas tersebut. Nenek tua membawa keong itu pulang dan merawatnya dengan penuh kasih sayang. Setiap hari, nenek tua itu pergi bekerja di ladang, meninggalkan keong emas sendirian di rumah. Namun, keajaiban terjadi. Setiap kali nenek tua pulang dari ladang, rumahnya menjadi bersih, makanan sudah terhidang di meja, dan semua pekerjaan rumah telah selesai. Nenek tua sangat heran dan ingin tahu siapa yang membantu melakukan semua pekerjaan tersebut.",
               "\n \n",
               "Suatu hari, nenek tua pura-pura pergi ke ladang, tetapi sebenarnya dia bersembunyi di dekat rumah untuk mengintip. Betapa terkejutnya dia saat melihat keong emas berubah menjadi putri yang cantik.",
               "\n",
               "Nenek tua kemudian keluar dari persembunyiannya dan bertanya kepada Candra Kirana, <em>\"Siapakah kamu, wahai gadis cantik?\"</em>",
               "\n \n",
               "Candra Kirana pun menceritakan kisahnya kepada nenek tua. <em>\"Aku adalah Putri Candra Kirana yang disihir menjadi keong emas oleh seorang penyihir jahat. Setiap kali aku sendirian, aku bisa kembali ke wujud asliku untuk sementara waktu.\"</em>",
               "\n \n",
               "Nenek tua merasa sangat kasihan kepada Candra Kirana dan berjanji akan membantunya kembali ke istana. Dengan bantuan nenek tua dan kebaikan hati Candra Kirana, penyihir jahat itu akhirnya dikalahkan dan sihirnya pun hilang. Candra Kirana kembali menjadi manusia sepenuhnya.",
               "\n \n",
               "Candra Kirana pun kembali ke istana dengan diantar oleh nenek tua. Ayahnya, Raja Kertamarta, sangat senang dan bersyukur karena putri kesayangannya kembali. Dewi Galuh, yang menyesali perbuatannya, meminta maaf kepada Candra Kirana dan mereka pun hidup rukun kembali.",
               "\n \n",
               "Akhirnya, Candra Kirana menikah dengan seorang pangeran tampan dari kerajaan tetangga dan mereka hidup bahagia selamanya.",
          ].join(""),
          morals: [
               "Dongeng Keong Emas mengajarkan bahwa <strong>kebaikan hati</strong> dan </strong>kesabaran</strong> akan selalu membawa kebahagiaan. Kejujuran dan kebaikan akan selalu mendapatkan balasan yang baik, dan orang yang jahat akan mendapatkan hukuman atas perbuatannya. Jadi, mari kita selalu bersikap baik dan tulus kepada semua orang.",
          ].join(""),
          synopsis: [
               "Putri Candra Kirana disihir menjadi keong emas oleh penyihir jahat. Ia pun dirawat oleh nenek tua, namun ketika nenek itu tahu identitas aslinya, ia pun membantunya melawan penyihir jahat.",
          ].join(""),
     },
     {
          id: "dgxlllmqcwmdo1dt",
		title: "Timun Emas",
		category: "Dongeng",
		origin: "Jawa Tengah",
          imageId: "403",
          storyDesc: [
               "Pada zaman dahulu kala, hiduplah seorang janda tua bernama Mbok Srini. Mbok Srini sangat merindukan seorang anak. Setiap hari, dia berdoa kepada Tuhan agar diberikan seorang anak. Suatu hari, ketika Mbok Srini sedang bekerja di ladang, seorang raksasa muncul di depannya.",
               "\n",
               "Raksasa itu berkata, <em>\"Mbok Srini, aku akan memberimu seorang anak, tapi dengan satu syarat. Ketika anak itu berusia 17 tahun, kamu harus memberikannya kepadaku.\"</em>",
               "\n \n",
               "Mbok Srini yang sangat ingin memiliki anak, setuju dengan syarat raksasa tersebut.",
               "\n \n",
               "Raksasa itu lalu memberikan sebutir biji mentimun kepada Mbok Srini dan berkata, <em>\"Tanamlah biji ini, dan kamu akan mendapatkan seorang anak.\"</em>",
               "\n \n",
               "Mbok Srini segera menanam biji mentimun tersebut. Tak lama kemudian, biji itu tumbuh menjadi tanaman mentimun yang besar dan sehat. Di antara buah-buah mentimun, ada satu yang berkilauan seperti emas. Mbok Srini memetik mentimun itu dan dengan hati-hati membukanya. Betapa terkejutnya Mbok Srini ketika menemukan seorang bayi perempuan yang cantik di dalamnya. Mbok Srini menamai bayi itu Timun Emas.",
               "\n \n",
               "Timun Emas tumbuh menjadi gadis yang cantik dan baik hati. Mbok Srini merawatnya dengan penuh kasih sayang. Tahun demi tahun berlalu, dan Timun Emas semakin besar. Ketika usianya mendekati 17 tahun, Mbok Srini menjadi sangat khawatir. Dia ingat janji yang dibuatnya kepada raksasa.",
               "\n \n",
               "Pada suatu malam, Mbok Srini bermimpi didatangi oleh seorang dewa yang memberitahunya untuk memberikan Timun Emas empat benda: biji mentimun, jarum, garam, dan terasi (pasta udang). Benda-benda ini akan membantu Timun Emas melawan raksasa jika dia datang menagih janji. Mbok Srini memberikan benda-benda tersebut kepada Timun Emas dan mengajarinya cara menggunakannya.",
               "\n \n",
               "Ketika Timun Emas berusia 17 tahun, raksasa itu datang untuk menagih janjinya. Timun Emas ketakutan, tetapi dia ingat nasihat Mbok Srini. Dengan cepat, dia berlari ke hutan sambil membawa empat benda pemberian Mbok Srini. Raksasa itu mengejarnya dengan langkah-langkah besar.",
               "\n \n",
               "Dalam pelariannya, Timun Emas melemparkan biji mentimun ke tanah. Ajaibnya, biji itu tumbuh menjadi tanaman mentimun yang sangat lebat dan melilit kaki raksasa. Namun, raksasa itu berhasil melepaskan diri dan terus mengejar Timun Emas.",
               "\n \n",
               "Kemudian, Timun Emas melemparkan jarum. Jarum itu berubah menjadi pohon bambu yang sangat tajam. Raksasa itu kesulitan melintasi hutan bambu tersebut, tetapi dia tetap bisa melanjutkan pengejarannya.",
               "\n \n",
               "Setelah itu, Timun Emas melemparkan garam. Garam itu berubah menjadi laut yang luas. Raksasa itu hampir tenggelam, tetapi dengan susah payah dia berhasil berenang melintasi laut tersebut.",
               "\n \n",
               "Terakhir, Timun Emas melemparkan terasi. Terasi itu berubah menjadi lautan lumpur yang mendidih. Raksasa itu tidak bisa melintasi lautan lumpur tersebut dan akhirnya tenggelam.",
               "\n \n",
               "Timun Emas berhasil kembali ke rumah dengan selamat. Mbok Srini sangat bahagia melihat Timun Emas selamat. Mereka berdua hidup bahagia selamanya tanpa gangguan dari raksasa lagi.",
          ].join(""),
          morals: [
               "Dongeng Timun Emas mengajarkan kita bahwa <strong>keberanian</strong> dan <strong>kecerdikan</strong> dapat mengalahkan kekuatan yang besar. Dengan tidak mudah menyerah dan menggunakan akal, kita dapat mengatasi berbagai rintangan dalam hidup.",
               "\n",
               "Selain itu, kisah ini juga mengajarkan pentingnya menjaga janji dan menghadapi konsekuensi dari perjanjian yang dibuat.",
          ].join(""),
          synopsis: [
               "Seorang janda bernama Mbok Srini ingin memiliki anak. Seekor raksasa pun muncul dan menjanjikan seorang anak, tapi dengan syarat diberikan kepadanya ketika ia berusia 17 tahun.",
          ].join(""),
     },
     {
          id: "dgf8uxolgybk6zyn",
		title: "Jaka Tarub",
		category: "Dongeng",
		origin: "Jawa Tengah",
          imageId: "404",
          storyDesc: [
               "Dahulu kala, di sebuah desa yang indah di Jawa,  hiduplah seorang pemuda bernama Jaka Tarub. Dia merupakan pemuda desa yang gemar berburu.",
               "\n \n",
               "Kemudian suaru hari, dia memutuskan untuk mencari burung di tengah hutan. Namun, meskipun telah berusaha sepanjang hari, ia tidak menemukan satupun burung. Akhirnya ia memutuskan untuk masuk ke hutan semakin dalam.",
               "\n",
               "Di tengah belantara, Jaka mendengar suara beberapa wanita yang sedang berbincang. Suara perempuan itu beradu dengan suara air gemericik. Karena penasaran, Jaka Tarub mencari sumber suara tersebut.",
               "\n \n",
               "Betapa terkejutnya dia saat melihat sekelompok bidadari yang tengah mandi di telaga. Paras para bidadari itu sangatlah cantik. Kemudian timbul sebuah ide nakal.",
               "\n \n",
               "Jaka Tarub diam-diam mengambil salah satu pakaian milik bidadari itu, dan kembali bersembunyi.",
               "\n \n",
               "Menjelang sore, para bidadari itu selesai mandi. Mereka mengenakan pakaian mereka kembali dan pulang menuju langit.",
               "\n \n",
               "Namun, ada satu bidadari yang tidak ikut pulang. Sebab, dia kehilangan pakaiannya. Bak pahlawan, Jaka Tarub pun muncul dan meminjamkan kain kepada bidadari itu. Bidadari bernama Nawang Wulan itu lantas diajak Jaka untuk tinggal di rumahnya.",
               "\n \n",
               "Nawang Wulan pun akhirnya tinggal di bumi, perlahan ia pun jatuh cinta pada Jaka Tarub dan memutuskan untuk menikah dengannya. Mereka hidup bahagia dan dikaruniai seorang anak bernama Nawangsih.",
               "\n \n",
               "Sebagai seorang bidadari tentu saja dia memiliki kesaktian. Setiap hari dia bisa menciptakan nasi yang cukup dimakan sekeluarga dengan hanya memasukkan sehelai padi ke dalam periuk.",
               "\n \n",
               "Namun, kesaktiannya itu bisa hilang jika ada orang yang membuka periuk saat dia memasak nasi. Dia selalu berpesan kepada Jaka Tarub untuk tidak membuka periuk itu.",
               "\n \n",
               "Suatu hari, ketika sedang memasak, Nawang Wulan ingin ssekalian mencuci pakaian. Dia berpesan kepada Jaka Tarub untuk mengasuh anak mereka.",
               "\n \n",
               "Saat Nawang Wulan sedang mencuci, muncul rasa penasaran Jaka Tarub. Meski sudah diperingatkan tetapi rasa penasarannya terlalu besar, dia pun akhirnya membuka periuk itu. Betapa terkejutnya Jaka saat dia melihat ternyata selama ini Nawang Wulan hanya memasak sehelai padi untuk mereka makan.",
               "\n \n",
               "Rasa penasaran itu akibatnya sangat besar. Kini, kesaktian Nawang Wulan lenyap. Sehingga ia harus memasak beras agar keluarganya bisa makan. Karena ini persediaan beras di lumbung yang selama ini tidak pernah berkurang lama-kelamaan mulai habis.",
               "\n \n",
               "Setiap hari Nawang Wulan mengambil persediaan beras di lumbung. Saat persediaan menipis, betapa terkejutnya dia ketika menemukan sehelai baju di lumbung. Baju itu merupakan bajunya yang hilang saat mandi di telaga.",
               "\n \n",
               "Nawang Wulan pun akhirnya sadar bahwa pakaian itu memang sengaja dicuri dan disembunyikan oleh Jaka Tarub. Dia lantas segera mengenakan pakaian itu kembali dan berubah menjadi bidadari.",
               "\n \n",
               "Setelah berpesan kepada Jaka Tarub untuk terus merawat anak mereka, akhirnya Nawang Wulan pulang kembali ke kayangan dan meninggalkan mereka di bumi.",
          ].join(""),
          morals: [
               "Dongeng Jaka Tarub adalah tentang <strong>kebaikan hati</strong>, <strong>pengorbanan</strong>, dan <strong>cinta yang tulus</strong>.",
               "\n",
               "Selain itu, kisah ini juga mengajarkan bahwa kebaikan hati, pengorbanan, dan cinta yang tulus adalah hal-hal yang sangat berharga dalam kehidupan.",
          ].join(""),
          synopsis: [
               "Jaka Tarub bertemu dengan tujuh bidadari yang sedang mandi. Karena jatuh cinta, ia mengambil salah satu pakaian bidadari agar ia tidak bisa kembali ke langit.",
          ].join(""),
     },
];

module.exports = stories;
