const storyList = [
     {
          id: "FBsYg3FUVEzNHnt3",
		title: "Si Kancil dan Buaya",
		category: "Fabel",
		location: "Nusantara",
          imageId: "",
		storyDesc: [
               "Pada suatu hari yang cerah, di sebuah hutan yang rindang, hiduplah seekor kancil kecil yang cerdik bernama Kancil. Kancil suka berpetualang di hutan, mencari makan dan bermain dengan teman-temannya. Suatu hari, setelah berkeliling hutan, Kancil merasa sangat haus. Dia ingin pergi ke sungai untuk minum air yang segar dan dingin.",
               "\n \n",
               "Saat Kancil sampai di tepi sungai, dia melihat ada banyak buaya sedang berjemur di sana. Kancil tahu bahwa buaya-buaya itu bisa sangat berbahaya. Dia berpikir keras, mencari cara agar bisa minum air tanpa dimakan oleh buaya-buaya tersebut. Tiba-tiba, Kancil mendapatkan ide yang sangat cerdik!",
               "\n \n",
               "Kancil mendekati salah satu buaya yang besar dan berkata dengan suara yang lantang,",
               "\n",
               "<em>\"Halo Buaya! Aku punya kabar baik! Raja Hutan ingin membagikan makanan kepada kalian semua. Tapi, Raja Hutan perlu tahu berapa jumlah buaya di sungai ini.\"</em>",
               "\n \n",
               "Buaya besar itu merasa senang mendengar kabar tersebut.",
               "\n",
               "<em>\"Benarkah, Kancil? Bagaimana caranya Raja Hutan akan menghitung kami\"</em> tanyanya.",
               "\n \n",
               "Kancil menjawab, ",
               "\n",
               "<em>\"Mudah sekali! Kalian semua harus berbaris dari sini sampai ke seberang sungai, agar aku bisa menghitung kalian satu per satu.\"</em>",
               "\n \n",
               "Buaya besar itu lalu memerintahkan semua buaya untuk berbaris dari tepi sungai sampai ke seberang. Mereka segera berbaris dengan rapi, menyambung dari satu buaya ke buaya lainnya.",
               "\n \n",
               "Kancil mulai melompat ke punggung buaya pertama sambil berkata,",
               "\n",
               "<em>\"Satu!\"</em>",
               "\n",
               "Lalu dia melompat ke punggung buaya kedua sambil berkata,",
               "\n",
               "<em>\"Dua!\"</em>",
               "\n",
               "Kancil terus melompat dari satu buaya ke buaya lainnya, sambil menghitung dengan keras,",
               "<em>\"Tiga, empat, lima...\"</em>",
               "\n",
               "Hingga akhirnya dia sampai di seberang sungai.",
               "\n \n",
               "Setelah sampai di seberang sungai, Kancil melompat ke tanah kering dan berkata,",
               "\n",
               "<em>\"Terima kasih, Buaya! Sekarang aku sudah tahu berapa jumlah kalian.\"</em>",
               "\n \n",
               "Buaya-buaya itu bertanya,",
               "\n",
               "\"Berapa jumlah kami, Kancil?\"",
               "\n \n",
               "Kancil tertawa dan berkata,",
               "\n",
               "<em>\"Jumlah kalian cukup banyak, tapi aku hanya butuh menyeberang sungai agar bisa minum air segar. Terima kasih sudah membantu! Selamat tinggal, Buaya!\"</em>",
               "\n \n",
               "Para buaya marah karena merasa tertipu, tetapi mereka tidak bisa berbuat apa-apa. Kancil sudah berada di seberang sungai dan minum air dengan aman. Kancil pun pergi dengan senang hati setelah minum air yang segar.",
          ].join(""),
     },
     {
          id: "SAjqL9feDywgacqJ",
		title: "Prabu Siliwangi",
		category: "Sage",
		location: "Jawa Barat",
          imageId: "",
		storyDesc: [
               "Pada zaman dahulu, di tanah Sunda yang subur dan penuh dengan keindahan alam, berdirilah sebuah kerajaan besar bernama Pajajaran. Kerajaan ini dipimpin oleh seorang raja yang sangat bijaksana dan gagah perkasa, bernama Prabu Siliwangi. Beliau sangat dicintai oleh rakyatnya karena kebijaksanaannya, keberaniannya, dan keadilannya.",
               "\n \n",
               "Setiap pagi, Prabu Siliwangi selalu bangun dengan semangat baru. Setelah matahari terbit, ia akan berjalan-jalan di sekitar istana untuk menyapa rakyatnya. Pada suatu hari, saat Prabu Siliwangi sedang berjalan di pasar, ia melihat seorang petani tua yang sedang bersedih. Prabu Siliwangi mendekati petani itu dan bertanya, ",
               "\n",
               "<em>\"Wahai petani, kenapa kau terlihat begitu sedih?\"</em>",
               "\n \n",
               "Petani itu menghela napas panjang dan berkata",
               "\n",
               "<em>\"Yang Mulia, ladang kami telah dirusak oleh tikus-tikus. Kami takut tidak akan ada panen tahun ini, dan kami tidak akan bisa memberi makan keluarga kami.\"</em>",
               "\n \n",
               "Prabu Siliwangi berpikir sejenak, lalu tersenyum dan berkata, ",
               "\n",
               "<em>\"Jangan khawatir, aku punya ide. Kita akan memelihara kucing-kucing di ladangmu. Mereka akan menjaga ladangmu dari tikus-tikus itu.\"</em>",
               "\n \n",
               "Petani itu pun mengikuti saran Prabu Siliwangi. Beberapa hari kemudian, ladangnya kembali subur dan tikus-tikus tidak berani mendekat lagi. Petani itu sangat berterima kasih kepada raja yang bijaksana.",
               "\n \n",
               "Namun, kebijaksanaan bukanlah satu-satunya keunggulan Prabu Siliwangi. Beliau juga sangat pemberani. Suatu hari, terdengar kabar bahwa sebuah kerajaan tetangga berencana untuk menyerang Pajajaran. Raja musuh itu sangat jahat dan ingin merebut tanah Pajajaran yang subur.",
               "\n \n",
               "Prabu Siliwangi segera mengumpulkan pasukannya dan berkata, ",
               "\n",
               "<em>\"Kita harus melindungi tanah kita dan rakyat kita. Jangan biarkan musuh merusak kedamaian kita.\"</em>",
               "\n",
               "Dengan penuh semangat, prajurit Pajajaran bersiap-siap untuk berperang.",
               "\n \n",
               "Ketika pertempuran dimulai, Prabu Siliwangi berada di barisan terdepan, memimpin pasukannya dengan keberanian luar biasa. Ia melawan musuh dengan gagah berani dan memberi semangat kepada prajuritnya.",
               "\n",
               "<em>\"Kita harus menang! Untuk Pajajaran!\"</em> seru Prabu Siliwangi.",
               "\n \n",
               "Dengan keberanian dan strategi cerdas Prabu Siliwangi, pasukan Pajajaran berhasil mengalahkan musuh. Raja musuh melarikan diri, dan Pajajaran kembali aman. Rakyat bersorak gembira dan mengadakan pesta besar untuk merayakan kemenangan mereka.",
               "\n \n",
               "Rakyat Pajajaran sangat bersyukur memiliki raja seperti Prabu Siliwangi. Di bawah kepemimpinannya, kerajaan selalu dalam keadaan damai dan sejahtera. Prabu Siliwangi selalu memastikan bahwa setiap orang hidup dengan bahagia dan damai.",
          ].join(""),
     },
     {
		id: "LGchskJBP_LSnWms",
		title: "Danau Toba dan Pulau Samosir",
		category: "Legenda",
		location: "Sumatra Utara",
          imageId: "",
		storyDesc: [
               "Pada suatu waktu yang sangat lama, di sebuah desa kecil yang dikelilingi oleh gunung-gunung hijau, hiduplah seorang pemuda bernama Toba. Toba adalah seorang petani yang rajin dan baik hati. Setiap hari, Toba bekerja di ladangnya, menanam padi dan sayuran.",
               "\n \n",
               "Suatu hari, saat Toba sedang memancing di sungai yang jernih, dia menangkap ikan yang sangat besar dan indah. Ikan itu berwarna keemasan dan berkilauan di bawah sinar matahari. Toba sangat senang dan membawa ikan itu pulang untuk dimasak.",
               "\n \n",
               "Namun, saat Toba hendak memasak ikan itu, tiba-tiba ikan tersebut berubah menjadi seorang gadis cantik.",
               "\n",
               "Toba terkejut dan bertanya, <em>\"Siapa kamu?\"</em>",
               "\n \n",
               "Gadis itu menjawab, \"Aku adalah putri dari kerajaan ikan. Karena kebaikan hatimu, aku diizinkan untuk menjadi manusia. Tapi ada satu syarat, kamu tidak boleh memberitahukan siapa pun tentang asal usulku sebagai ikan.\"",
               "\n \n",
               "Toba setuju dan mereka menikah. Mereka hidup bahagia dan memiliki seorang anak laki-laki bernama Samosir. Samosir adalah anak yang cerdas dan aktif, tetapi dia juga sangat nakal dan suka makan banyak.",
               "\n \n",
               "Suatu hari, Toba marah besar karena Samosir menghabiskan semua makanan di rumah. Dalam kemarahannya,",
               "\n",
               "Toba lupa akan janjinya dan berkata, <em>\"Dasar anak ikan!\"</em>",
               "\n \n",
               "Seketika itu juga, langit menjadi gelap dan petir menyambar. Istri Toba yang mendengar kata-kata itu merasa sangat sedih.",
               "\n",
               "Dia berkata, <em>\"Toba, kamu telah melanggar janjimu. Sekarang aku harus kembali ke asal usulku.\"</em>",
               "\n \n",
               "Istri Toba segera berubah kembali menjadi ikan dan melompat ke sungai. Air sungai itu kemudian meluap dan membanjiri seluruh desa. Toba dan Samosir berlari ke tempat yang tinggi untuk menyelamatkan diri.",
               "\n \n",
               "Banjir itu tidak berhenti dan terus meluas hingga membentuk sebuah danau besar yang sekarang dikenal sebagai Danau Toba. Di tengah danau itu, ada sebuah pulau yang dinamai sesuai dengan nama anak mereka, Pulau Samosir.",
          ].join(""),
	},
	{
		id: "DGkeMnmpb_PRTY8f",
		title: "Cinderalas",
		category: "Dongeng",
		location: "Jawa Timur",
          imageId: "",
		storyDesc: [
               "Pada suatu masa di kerajaan Jenggala, hiduplah seorang raja yang bijaksana bernama Raden Putra. Sang raja memiliki seorang permaisuri yang cantik dan baik hati. Namun, kebahagiaan mereka terusik oleh perbuatan jahat seorang selir yang iri hati. Selir tersebut ingin menjadi satu-satunya istri raja dan merencanakan sebuah fitnah untuk menjatuhkan permaisuri. Ia bersekongkol dengan tabib istana untuk memfitnah permaisuri dengan tuduhan bahwa permaisuri telah meracuni raja.",
               "\n \n",
               "Tabib yang licik itu pura-pura memeriksa kesehatan raja dan menyatakan bahwa raja telah diracuni oleh permaisuri. Mendengar kabar itu, Raden Putra sangat marah dan sedih. Tanpa penyelidikan lebih lanjut, ia memerintahkan agar permaisuri dibuang ke hutan belantara. Prajurit yang bertugas mengusir permaisuri merasa iba, tetapi ia tidak bisa melawan perintah raja. Di tengah hutan, permaisuri ditinggalkan sendirian. Tak lama setelah ditinggalkan, permaisuri melahirkan seorang bayi laki-laki yang diberi nama Cindelaras.",
               "\n \n",
               "Cindelaras tumbuh menjadi anak yang kuat dan cerdas di tengah hutan. Ia dibesarkan oleh ibunya dengan penuh kasih sayang. Pada suatu hari, seekor ayam jantan muncul dan menjadi sahabat Cindelaras. Ayam tersebut bukan ayam biasa, melainkan ayam ajaib yang bisa berbicara. Suatu pagi, ayam itu berkata kepada Cindelaras,",
               "\n",
               "<em>\"Majikanku adalah Cindelaras, rumahnya di tengah hutan, anak Raden Putra.\"</em>",
               "\n",
               "Mendengar hal itu, Cindelaras terkejut dan menanyakan lebih lanjut kepada ibunya. Akhirnya, ibunya menceritakan asal-usul mereka yang sebenarnya.",
               "\n \n",
               "Cindelaras merasa terpanggil untuk mencari kebenaran dan menuntut keadilan. Bersama ayam jantannya, ia memutuskan pergi ke istana Jenggala. Dalam perjalanan menuju istana, keajaiban ayam Cindelaras menyebar ke seluruh negeri. Banyak orang yang kagum dengan ayam tersebut, karena selain bisa berbicara, ayam itu juga sangat kuat dan selalu menang dalam setiap pertarungan ayam. Berita tentang ayam ajaib ini akhirnya sampai ke telinga Raden Putra.",
               "\n \n",
               "Raden Putra yang penasaran mengundang Cindelaras untuk datang ke istana dan mengadu ayam jantannya. Setibanya di istana, Cindelaras langsung dipertemukan dengan raja. Raja menantang Cindelaras untuk mengadu ayamnya dengan ayam kerajaan. Dengan tenang, Cindelaras menerima tantangan itu. Dalam pertarungan tersebut, ayam Cindelaras dengan mudah mengalahkan ayam kerajaan. Raden Putra merasa takjub dan penasaran dengan pemuda ini.",
               "\n",
               "Setelah pertandingan, ayam Cindelaras kembali berbicara, <em>\"Majikanku adalah Cindelaras, rumahnya di tengah hutan, anak Raden Putra.\"</em>",
               "\n",
               "Raja terkejut dan meminta Cindelaras untuk menceritakan lebih lanjut. Cindelaras pun menceritakan kisah hidupnya serta fitnah yang menimpa ibunya. Mendengar cerita itu, Raden Putra tersentak dan menyadari kesalahannya. Ia segera memanggil prajurit yang dulu mengusir permaisuri dan meminta mereka menjemputnya kembali.",
               "\n \n",
               "Permaisuri yang telah lama hidup di hutan akhirnya dibawa kembali ke istana. Raden Putra meminta maaf kepada permaisuri dan Cindelaras atas kesalahpahaman yang telah terjadi. Ia juga menghukum selir yang licik dan tabib yang telah memfitnah permaisuri. Keadilan pun ditegakkan di kerajaan Jenggala. ",
               "\n \n",
               "Raden Putra sangat bangga dengan keberanian dan keteguhan hati Cindelaras. Ia mengangkat Cindelaras sebagai putra mahkota. Cindelaras tumbuh menjadi pemuda yang bijaksana dan siap untuk memimpin kerajaan di masa depan. Kisah Cindelaras menjadi inspirasi bagi rakyat Jenggala tentang pentingnya kejujuran dan kebenaran.",
               "\n \n",
               "Kerajaan Jenggala pun kembali damai dan sejahtera. Cindelaras bersama ayam ajaibnya menjadi legenda yang diceritakan dari generasi ke generasi. Mereka diingat sebagai simbol keadilan dan keberanian yang abadi dalam hati masyarakat.",
          ].join(""),
	},
     {
          id: "SGevKvOGavmPGFMe1",
		title: "Jaka Tingkir",
		category: "Sage",
		location: "Jawa Tengah",
          imageId: "",
		storyDesc: [
               "Pada zaman dahulu kala, di sebuah desa kecil di Jawa Tengah, hiduplah seorang pemuda yang bernama Jaka Tingkir. Jaka Tingkir adalah seorang pemuda yang gagah berani dan memiliki kekuatan yang luar biasa. Ia tinggal bersama ibunya di sebuah rumah sederhana. Walaupun hidup sederhana, Jaka Tingkir selalu bersemangat dan penuh kebaikan.",
               "\n \n",
               "Suatu hari, Jaka Tingkir memutuskan untuk pergi merantau ke kerajaan Pajang. Ia ingin mencari pengalaman dan belajar lebih banyak tentang kehidupan.",
               "Sebelum pergi, Jaka Tingkir berpamitan kepada ibunya, <em>\"Ibu, izinkan aku pergi merantau ke Pajang. Aku ingin mencari ilmu dan pengalaman yang lebih banyak.\"</em> kata Jaka Tingkir",
               "\n \n",
               "Ibunya memberikan restu dengan berat hati.",
               "\n",
               "<em>\"Hati-hati di jalan, anakku. Ingat selalu nasihat ibu dan jangan pernah lupa untuk berbuat baik,\"</em> pesan ibunya.",
               "\n \n",
               "Jaka Tingkir kemudian memulai perjalanannya. Di tengah perjalanan, ia harus melewati hutan yang lebat dan sungai yang deras. Namun, dengan keberaniannya, ia berhasil melewati semua rintangan tersebut. Akhirnya, Jaka Tingkir tiba di kerajaan Pajang.",
               "\n \n",
               "Di kerajaan Pajang, Jaka Tingkir mengabdi pada Sultan Hadiwijaya. Ia bekerja keras dan menunjukkan keberanian serta kesetiaannya. Suatu hari, terjadi kerusuhan di kerajaan. Seekor banteng besar mengamuk dan membuat kekacauan. Banyak prajurit kerajaan yang mencoba menaklukkan banteng tersebut, namun semuanya gagal.",
               "\n \n",
               "Mendengar hal itu, Jaka Tingkir menawarkan diri untuk menghadapi banteng yang mengamuk. Sultan Hadiwijaya mengizinkannya dengan harapan Jaka Tingkir bisa mengatasi masalah tersebut. Dengan penuh keberanian, Jaka Tingkir mendekati banteng yang besar dan ganas itu. Dengan kekuatannya yang luar biasa, ia berhasil menaklukkan banteng dan menenangkannya.",
               "\n",
               "Sultan Hadiwijaya sangat terkesan dengan keberanian dan kemampuan Jaka Tingkir. Sebagai tanda terima kasih, Sultan memberikan hadiah berupa jabatan penting di kerajaan. Jaka Tingkir kemudian diangkat menjadi seorang panglima yang bertanggung jawab atas keamanan kerajaan.",
               "\n",
               "Jaka Tingkir terus bekerja dengan rajin dan penuh dedikasi. Ia selalu berusaha melindungi kerajaan dari segala bahaya. Berkat keberaniannya, Jaka Tingkir menjadi sosok yang dihormati dan dikagumi oleh semua orang di kerajaan Pajang.",
               "\n \n",
               "Pada akhirnya, Jaka Tingkir tidak hanya dikenal sebagai pemuda yang gagah berani, tetapi juga sebagai pemimpin yang bijaksana. Ia selalu mengingat pesan ibunya untuk berbuat baik dan membantu sesama. Kehidupannya menjadi inspirasi bagi banyak orang.",
          ].join(""),
	},
     {
          id: "SGcgfx5moDasSr6R",
		title: "Sangkuriang",
          category: "Sage",
          location: "Jawa Barat",
          imageId: "",
		storyDesc: [
               "Pada zaman dahulu kala, di sebuah kerajaan di Jawa Barat, hiduplah seorang putri yang sangat cantik dan cerdas bernama Dayang Sumbi. Dayang Sumbi tinggal di sebuah istana megah bersama ayahnya, sang raja. Namun, meskipun memiliki segala kemewahan, Dayang Sumbi merasa kesepian.",
               "\n \n",
               "Suatu hari, ketika sedang menenun, benang tenunannya jatuh ke lantai. Dayang Sumbi yang malas mengambilnya berkata",
               "\n",
               "<em>\"Siapa pun yang mengambilkan benangku, jika ia laki-laki akan menjadi suamiku, dan jika perempuan akan menjadi saudariku.\"</em>",
               "\n \n",
               "Tanpa disangka, seekor anjing bernama Tumang yang mengambilkan benang tersebut. Tumang sebenarnya adalah dewa yang dikutuk menjadi anjing. Karena sudah berjanji akhirnya Dayang Sumbi menikahi Tumang dan mereka memiliki seorang anak laki-laki yang diberi nama Sangkuriang. Sangkuriang tumbuh menjadi anak yang tangkas dan kuat. Namun, ia tidak mengetahui bahwa Tumang adalah ayahnya.",
               "\n \n",
               "Suatu hari, Dayang Sumbi menyuruh Sangkuriang pergi berburu dan meminta hati dari seekor kijang. Namun, Sangkuriang gagal mendapatkan kijang dan, karena takut mengecewakan ibunya, ia membunuh Tumang dan mengambil hatinya. Ketika Dayang Sumbi mengetahui kebenarannya, ia marah besar dan mengusir Sangkuriang.",
               "\n \n",
               "Bertahun-tahun kemudian, Sangkuriang yang sudah dewasa kembali ke desanya. Ia bertemu dengan Dayang Sumbi yang tetap terlihat muda dan cantik karena mendapatkan keabadian dari para dewa. Sangkuriang tidak mengenali ibunya sendiri dan jatuh cinta padanya. Mereka berencana untuk menikah.",
               "\n \n",
               "Namun suatu hari, Dayang Sumbi melihat bekas luka di kepala Sangkuriang yang membuatnya sadar bahwa pria itu adalah anaknya. Ia pun berusaha menghentikan pernikahan tersebut dengan memberikan syarat yang sangat sulit.",
               "\n",
               "<em>\"Aku akan menikah denganmu jika kamu bisa membuat danau dan sebuah perahu besar dalam semalam,\"</em> kata Dayang Sumbi.",
               "\n \n",
               "Dengan bantuan kekuatan gaibnya, Sangkuriang hampir menyelesaikan tugas tersebut. Dayang Sumbi yang khawatir akan berhasilnya Sangkuriang, meminta penduduk desa untuk membantunya dengan menumbuk padi dan menyalakan api besar di timur, membuat ayam berkokok lebih awal seolah-olah fajar sudah tiba.",
               "\n \n",
               "Sangkuriang merasa ditipu dan sangat marah. Dalam kemarahannya, ia menendang perahu yang hampir selesai itu hingga terbalik. Perahu tersebut berubah menjadi gunung yang kini dikenal sebagai Gunung Tangkuban Perahu, yang berarti 'perahu terbalik'.",
               "\n \n",
               "Gunung Tangkuban Perahu masih bisa dilihat hingga kini, mengingatkan kita akan kisah cinta dan tragedi antara Sangkuriang dan Dayang Sumbi."
          ].join(""),
     },

     {
          id: "SGMWGycNzRho6evy",
          title: "Rawa Pening",
          category: "Sage",
          location: "Jawa Tengah",          
          imageId: "",
		storyDesc: [
               "Pada zaman dahulu kala, di sebuah desa kecil di Jawa Tengah, hiduplah seorang anak kecil bernama Baru Klinthing. Baru Klinthing adalah seorang anak yang luar biasa. Ia sebenarnya adalah inkarnasi dari seekor naga yang memiliki kekuatan ajaib. Meskipun begitu, Baru Klinthing tumbuh seperti anak-anak lainnya di desa tersebut.",
               "\n \n",
               "Suatu hari, Baru Klinthing berjalan-jalan ke desa-desa sekitar untuk mencari makanan. Ia merasa sangat lapar dan berharap ada yang bersedia memberinya makan. Namun, semua penduduk desa menolak dan mengusirnya. Hanya seorang nenek tua yang merasa kasihan dan memberikan makanan kepada Baru Klinthing.",
               "\n",
               "<em>\"Terima kasih, Nek. Engkau sangat baik hati,\"</em> kata Baru Klinthing sambil makan dengan lahap.",
               "\n \n",
               "Setelah makan, Baru Klinthing memberikan pesan kepada nenek itu. <em>\"Nenek, tolong siapkan lesung di atas pohon. Sebentar lagi, desa ini akan tenggelam.\"</em> Nenek itu mengikuti saran Baru Klinthing tanpa bertanya lebih lanjut.",
               "\n \n",
               "Kemudian, Baru Klinthing kembali ke desa dan menancapkan sebatang lidi ke tanah. Ia menantang penduduk desa untuk mencabut lidi tersebut, tetapi tak seorang pun yang berhasil. Akhirnya, Baru Klinthing sendiri yang mencabut lidi itu.",
               "\n \n",
               "Begitu lidi tercabut, air memancar deras dari lubang yang ditinggalkan lidi tersebut. Air tersebut semakin lama semakin banyak dan menenggelamkan seluruh desa. Semua penduduk desa panik dan mencoba menyelamatkan diri, tetapi hanya nenek tua yang selamat karena ia mengikuti saran Baru Klinthing.",
               "\n \n",
               "Desa yang tenggelam tersebut akhirnya menjadi sebuah danau besar yang dikenal sebagai Rawa Pening. Danau itu masih ada hingga kini, sebagai pengingat akan cerita tentang Baru Klinthing dan kebijaksanaan nenek tua yang baik hati.",
               "\n \n",
               "Cerita ini mengajarkan kita tentang pentingnya bersikap baik kepada siapa pun, bahkan kepada orang yang tidak kita kenal. Kebaikan hati nenek tua tersebut menyelamatkan nyawanya, sementara penduduk desa yang lain mengalami nasib buruk karena keegoisan dan ketidakpedulian mereka."               
          ].join(""),
     },

     {
          id: "SGbmTzLKH6Joev6j",
          title: "Malin Kundang",
          category: "Sage",
          location: "Sumatera Barat",          
          imageId: "",
		storyDesc: [
               "Pada zaman dahulu kala, di sebuah desa kecil di Sumatera Barat, hiduplah seorang pemuda bernama Malin Kundang. Malin Kundang adalah anak tunggal dari seorang janda miskin. Mereka hidup sangat sederhana, tetapi penuh kasih sayang dan kebahagiaan.",
               "\n \n",
               "Suatu hari, Malin Kundang memutuskan untuk merantau demi mencari peruntungan dan membantu ibunya keluar dari kemiskinan. Dengan berat hati, ibunya melepas kepergiannya.",
               "\n",
               "<em>\"Hati-hati di perjalanan, anakku. Ingat selalu nasihat ibu dan jangan pernah lupa untuk berbuat baik,\"</em> pesan ibunya.",
               "\n \n",
               "Malin Kundang kemudian memulai perjalanannya. Ia bekerja keras dan berjuang di negeri orang. Setelah bertahun-tahun, usaha Malin membuahkan hasil. Ia menjadi seorang pedagang kaya raya dan menikah dengan seorang wanita cantik dari keluarga bangsawan.",
               "\n \n",
               "Suatu hari, Malin Kundang memutuskan untuk pulang ke desanya dengan kapal besar dan mewah. Ketika mendengar kabar bahwa Malin Kundang telah kembali, ibunya sangat gembira dan bergegas menyambutnya di pelabuhan. Namun, alangkah terkejutnya sang ibu ketika Malin Kundang tidak mengenalinya dan malah mengusirnya.",
               "\n \n",
               "Malin Kundang merasa malu mengakui ibunya yang berpakaian lusuh di hadapan istri dan awak kapalnya. Dengan hati hancur, sang ibu berdoa kepada Tuhan,",
               "\n",
               "<em>\"Ya Tuhan, jika benar dia anakku, kutuklah dia menjadi batu jika ia benar-benar durhaka.\"</em>",
               "\n \n",
               "Tak lama setelah itu, langit mendadak gelap dan badai besar melanda. Kapal Malin Kundang hancur diterjang ombak. Malin Kundang yang menyesali perbuatannya, perlahan berubah menjadi batu. Batu tersebut masih bisa dilihat di pantai Air Manis hingga kini, menyerupai sosok manusia yang sedang bersujud.",
          ].join(""),
          morals: [
               "Cerita Malin Kundang mengajarkan kita tentang <strong>pentingnya berbakti kepada orang tua</strong> dan <strong>menghargai asal-usul kita</strong>. Kisah ini juga memperingatkan kita tentang <strong>akibat dari kesombongan dan ketidaksetiaan</strong> terhadap keluarga.",
          ].join(""),
     },
];

module.exports = storyList;
